(() => {
 'use strict';const {el,check}=Raben;
 const canonical=(bucket,name)=>['raben-media','raben-public'].includes(bucket)&&(bucket==='raben-media'?/^[a-f0-9-]{36}\/[a-f0-9-]{36}\.(jpg|png|webp|mp3)$/:/^[a-f0-9-]{36}\.(jpg|png|webp|mp3)$/).test(name);
 const sha=async bytes=>Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',bytes))).map(b=>b.toString(16).padStart(2,'0')).join('');
 const manifest=async(data,entries,part,complete)=>{
  const files=[];for(const [path,bytes] of Object.entries(entries))if(path.startsWith('files/'))files.push({path,size:bytes.length,sha256:await sha(bytes)});
  return {application:'schwarze-raben-backup',version:2,backupId:data.exportedAt,part,complete,expected:(data.files||[]).map(f=>({path:'files/'+f.bucket+'/'+f.name,size:Number(f.size||0)})),files};
 };
 const finish=async(ctx,count)=>{await ctx.authorize();await check(Raben.client().from('raben_backup_runs').upsert({user_id:ctx.actor.user_id,completed_at:new Date().toISOString(),file_count:count}));};
 const status=async(ctx,host)=>{const epoch=ctx.epoch,rows=await check(Raben.client().from('raben_backup_runs').select('completed_at,file_count').order('completed_at',{ascending:false}).limit(1));if(ctx.disposed||ctx.epoch!==epoch)return;host.append(el('p','field-note',rows[0]?'Letzte abgeschlossene Mediensicherung: '+new Date(rows[0].completed_at).toLocaleString('de-DE')+' · '+rows[0].file_count+' Dateien.':'Noch keine abgeschlossene Mediensicherung vermerkt.'));};
 const validate=async files=>{
  let backup=null,backupId=null,total=0,complete=false;const found=new Map(),expected=new Map(),parts=new Set();
  if(!files.length)throw new Error('Bitte wähle die ZIP-Teile einer Sicherung aus.');
  for(const file of files){if(file.size>80*1024*1024)throw new Error('Ein ZIP-Teil ist zu groß. Prüfe kleinere Originalteile.');
   const bytes=new Uint8Array(await file.arrayBuffer()),entries=fflate.unzipSync(bytes,{filter:entry=>{if(entry.originalSize>52*1024*1024)throw new Error('Eine Datei ist größer als das Uploadlimit.');return true;}});
   if(!entries['backup.json']||!entries['manifest.json'])throw new Error('Dieses ZIP enthält kein neues Sicherungsmanifest. Ältere Sicherungen lassen sich unten einzeln prüfen.');
   const data=JSON.parse(fflate.strFromU8(entries['backup.json'])),m=JSON.parse(fflate.strFromU8(entries['manifest.json']));
   if(data.application!=='schwarze-raben'||m.application!=='schwarze-raben-backup'||m.version!==2||!Array.isArray(m.files)||!Array.isArray(m.expected)||m.backupId!==data.exportedAt)throw new Error('Ungültiges Sicherungsmanifest.');
   if(backupId&&backupId!==m.backupId)throw new Error('Die ausgewählten ZIP-Teile gehören zu verschiedenen Sicherungen.');if(parts.has(m.part))throw new Error('Ein ZIP-Teil wurde doppelt ausgewählt.');parts.add(m.part);backupId=m.backupId;backup=data;complete ||=m.complete===true;
   for(const f of m.expected){const parts=f.path?.split('/')||[],bucket=parts[1],name=parts.slice(2).join('/');if(parts[0]!=='files'||!canonical(bucket,name)||!Number.isFinite(f.size))throw new Error('Ungültiger Dateipfad im Manifest.');expected.set(f.path,f);}
   for(const f of m.files){const content=entries[f.path];if(!expected.has(f.path)||!content||content.length!==f.size||await sha(content)!==f.sha256)throw new Error('Eine Datei fehlt oder stimmt nicht mit ihrer Prüfsumme überein.');if(found.has(f.path))throw new Error('Eine Mediendatei kommt mehrfach vor.');total+=content.length;if(total>256*1024*1024)throw new Error('Prüfe bei sehr großen Sicherungen jeweils weniger ZIP-Teile. Fehlende Teile werden angezeigt.');found.set(f.path,content);}
   if(Object.keys(entries).some(path=>path!=='backup.json'&&path!=='manifest.json'&&!m.files.some(f=>f.path===path)))throw new Error('Unerwartete Datei in einem ZIP-Teil.');
  }
  return {backup,found,expected,missing:[...expected.keys()].filter(path=>!found.has(path)),complete,total,parts:parts.size};
 };
 const wizard=ctx=>{
  const {button,field}=RabenExpansion,card=el('article','hub-card backup-summary'),pick=field('Alle ZIP-Teile derselben Sicherung auswählen','file');pick.input.accept='.zip,application/zip';pick.input.multiple=true;const summary=el('div','backup-manifest');card.append(el('h3','','Sicherung prüfen und fehlende Dateien wiederherstellen'),el('p','field-note','Die Vorschau prüft Dateipfade, SHA-256-Prüfsummen und fehlende Teile. Lade zuerst benötigte Dateien zurück und stelle anschließend unten die geprüften Inhalte wieder her. Vorhandene Dateien werden beibehalten.'),pick.wrap,summary);ctx.list.prepend(card);let data=null;
  pick.input.addEventListener('change',async()=>{const epoch=ctx.epoch;summary.replaceChildren(el('p','field-note','ZIP-Teile werden geprüft …'));try{await ctx.authorize();data=await validate(Array.from(pick.input.files||[]));if(ctx.disposed||ctx.epoch!==epoch)return;summary.replaceChildren(el('p','field-note',data.parts+' Teil(e) geprüft · '+data.found.size+' / '+data.expected.size+' Dateien vorhanden · '+RabenMedia.bytes(data.total)),el('p','field-note',data.missing.length?'Fehlende Dateien: '+data.missing.length+' · Wähle zusätzlich die fehlenden Teile aus.':data.complete?'Alle erwarteten Dateien und der letzte Sicherungsteil sind vorhanden.':'Alle erwarteten Dateien sind da; der abschließende Sicherungsteil fehlt.'));
    const backend=await check(Raben.client().rpc('raben_storage_inventory'));if(ctx.disposed||ctx.epoch!==epoch)return;const current=new Set(backend.map(f=>'files/'+f.bucket+'/'+f.name));
    for(const [path,bytes] of data.found){const split=path.split('/'),bucket=split[1],name=split.slice(2).join('/'),line=el('p','field-note',(current.has(path)?'Vorhanden: ':'Fehlt im Speicher: ')+path);summary.append(line);if(!current.has(path))line.append(button(ctx,'Datei wiederherstellen',async()=>{if(!confirm(bucket==='raben-public'?'Diese Datei wieder öffentlich bereitstellen?':'Diese fehlende interne Datei wiederherstellen?'))return;const type=name.endsWith('.mp3')?'audio/mpeg':name.endsWith('.jpg')?'image/jpeg':name.endsWith('.png')?'image/png':'image/webp',file=new File([bytes],name.split('/').pop(),{type});const progress=RabenMedia.progressControls();line.append(progress.wrap);await RabenMedia.uploadOriginal(ctx,file,name,bucket,progress);ctx.report('Datei wiederhergestellt.');}));}
    const save=el('a','button outline small-button','Geprüfte backup.json herunterladen'),url=URL.createObjectURL(new Blob([JSON.stringify(data.backup,null,2)],{type:'application/json'}));ctx.urls.add(url);save.href=url;save.download='gepruefte-backup.json';summary.append(save);stockPreview(ctx,data.backup,summary);
   }catch(e){data=null;summary.replaceChildren(el('p','status-message',e.message||'Sicherung konnte nicht geprüft werden.'));}
  });return card;
 };
 const stockPreview=(ctx,backup,host)=>{const rows=backup.expansion?.stockItems||[];if(!rows.length)return;const details=el('details','');details.append(el('summary','','Lagerbestände aus dieser Sicherung prüfen'));rows.forEach(row=>{const line=el('p','field-note',row.name+' · '+row.quantity+' '+row.unit);line.append(RabenExpansion.button(ctx,'Bestand prüfen',async()=>{const current=await check(Raben.client().from('raben_stock_items').select('id,quantity,revision').eq('id',row.id).limit(1));const present=current[0];const preview=el('div','backup-manifest');preview.append(el('p','field-note','Aktuell: '+(present?.quantity||0)+' · aus Sicherung: '+row.quantity+' · Anpassung: '+(Number(row.quantity)-Number(present?.quantity||0))),RabenExpansion.button(ctx,'Geprüften Bestand übernehmen',async()=>{if(!confirm('Diese Bestandsanpassung als neue Lagerbewegung buchen?'))return;await check(Raben.client().rpc('raben_restore_stock',{p_row:row,p_expected:present?.revision??null}));ctx.report('Lagerbestand mit protokollierter Anpassung wiederhergestellt.');}));line.append(preview);}));details.append(line);});host.append(details);};
 window.RabenBackup={manifest,finish,status,wizard,validate,canonical};
})();
