(() => {
 'use strict';const {el,check}=Raben;let state=null,manifestSource='',manifestData=null,manifestUrl='',channel;
 const fallback=()=>new URL('assets/clan-emblem.svg',Raben.config.siteUrl).href;
 const source=row=>row?.image_path&&/^[a-f0-9-]{36}[.]png$/.test(row.image_path)?Raben.client().storage.from('raben-public').getPublicUrl(row.image_path).data.publicUrl:fallback();
 const manifest=async row=>{const node=document.querySelector('link[rel="manifest"]');if(!node)return;if(!manifestSource)manifestSource=node.href;if(!row?.image_path){node.href=manifestSource;if(manifestUrl){URL.revokeObjectURL(manifestUrl);manifestUrl='';}return;}try{if(!manifestData){const response=await fetch(manifestSource);manifestData=await response.json();}const data=structuredClone(manifestData);for(const key of ['id','start_url','scope'])if(data[key])data[key]=new URL(data[key],manifestSource).href;const image=source(row);data.icons=[{src:image,sizes:'512x512',type:'image/png',purpose:'any'}];for(const shortcut of data.shortcuts||[]){shortcut.url=new URL(shortcut.url,manifestSource).href;shortcut.icons=data.icons;}const old=manifestUrl;manifestUrl=URL.createObjectURL(new Blob([JSON.stringify(data)],{type:'application/manifest+json'}));node.href=manifestUrl;if(old)URL.revokeObjectURL(old);}catch(_){}};
 const apply=row=>{state=row;const url=source(row);document.querySelectorAll('[data-clan-emblem]').forEach(img=>img.src=url);document.querySelectorAll('link[rel="icon"],link[rel="apple-touch-icon"]').forEach(link=>{if(row?.image_path){link.href=url;link.type='image/png';}else if(link.rel==='icon'){link.href=new URL('favicon.svg',Raben.config.siteUrl).href;link.type='image/svg+xml';}else link.href=new URL('app/icons/icon-180.png',Raben.config.siteUrl).href;});manifest(row);};
 const load=async()=>{if(!Raben.configured?.())return;try{const row=await check(Raben.client().from('raben_branding').select('image_path,revision').eq('id',1).single());apply(row);}catch(_){}};
 const png=async file=>{await RabenMedia.validateFile(file,false);const bitmap=await createImageBitmap(file,{imageOrientation:'from-image'});try{const canvas=document.createElement('canvas');canvas.width=canvas.height=512;const context=canvas.getContext('2d'),ratio=Math.min(480/bitmap.width,480/bitmap.height),w=bitmap.width*ratio,h=bitmap.height*ratio;context.drawImage(bitmap,(512-w)/2,(512-h)/2,w,h);const blob=await new Promise(resolve=>canvas.toBlob(resolve,'image/png'));if(!blob)throw new Error('invalid_emblem');return new File([blob],'clanwappen.png',{type:'image/png'});}finally{bitmap.close();}};
 const editor=async ctx=>{
  if(ctx.actor.role!=='admin')throw {code:'42501'};const e=ctx.epoch;let row=await check(Raben.client().from('raben_branding').select('*').eq('id',1).single());if(ctx.disposed||ctx.epoch!==e)return;
  const f=el('form','hub-editor settings-form'),heading=el('h3','','Das Wappen eures Clans'),preview=el('img','emblem-preview');preview.src=source(row);preview.alt='Aktuelles Clanwappen';const label=el('label','form-field','Eigenes Clanwappen hochladen'),input=el('input','');input.type='file';input.accept='image/jpeg,image/png,image/webp';label.append(input);const controls=RabenMedia.progressControls(),save=el('button','button small-button','Clanwappen speichern');save.type='submit';
  let chosen=null,prepared=null,path=null;input.addEventListener('change',async()=>{prepared=null;path=null;chosen=input.files?.[0]||null;ctx.dirty=true;if(chosen){try{await RabenMedia.validateFile(chosen,false);if(ctx.disposed||ctx.epoch!==e)return;const url=URL.createObjectURL(chosen);ctx.urls.add(url);preview.src=url;}catch(error){ctx.report(RabenMedia.errorMessage(error),true);}}});
  const saved=value=>{row=value;apply(row);preview.src=source(row);ctx.dirty=false;input.value='';chosen=prepared=path=null;channel?.postMessage(row);};
  const reset=el('button','button outline small-button','Raben auf nordischem Schild verwenden');reset.type='button';reset.addEventListener('click',async()=>{reset.disabled=true;try{await ctx.authorize();saved(await check(Raben.client().rpc('raben_save_emblem',{p_path:null,p_expected:row.revision})));ctx.report('Das nordische Rabenwappen ist aktiv.');}catch(error){ctx.report(Raben.errorMessage(error),true);}finally{reset.disabled=false;}});
  f.append(heading,el('p','field-note','Dieses Wappen erscheint auf der Website, im Clanbereich und in der Admin-App. Du kannst es jederzeit durch ein eigenes Bild ersetzen. Die installierte App übernimmt Symboländerungen nach Maßgabe des Browsers.'),preview,label,el('p','field-note','JPG, PNG oder WebP · bis 50 MB. Das Bild wird ohne Abschneiden passend in ein quadratisches App-Symbol gesetzt.'),controls.wrap,save,reset);ctx.list.append(f);
  f.addEventListener('submit',async event=>{event.preventDefault();if(save.disabled)return;save.disabled=true;try{await ctx.authorize();if(!chosen)throw new Error('file_required');if(!prepared){prepared=await png(chosen);path=crypto.randomUUID()+'.png';}const uploaded=await RabenMedia.upload(ctx,prepared,ctx.actor.user_id,controls,false,path,'raben-public');if(ctx.disposed||ctx.epoch!==e)return;saved(await check(Raben.client().rpc('raben_save_emblem',{p_path:uploaded,p_expected:row.revision})));ctx.report('Clanwappen gespeichert und auf dieser Seite übernommen.');}catch(error){if(!ctx.disposed&&ctx.epoch===e)ctx.report(RabenMedia.errorMessage(error)||Raben.errorMessage(error),true);}finally{save.disabled=false;}});
 };
 window.RabenBranding={load,apply,editor,png,source};if(window.BroadcastChannel){channel=new BroadcastChannel('raben-clanwappen');channel.onmessage=event=>{if(event.data?.revision)apply(event.data);};}load();
})();
