(() => {
  'use strict';const {el,check}=Raben;
  const labels={home:'Mein Clanstart',searchAll:'Clansuche',notices:'🔔 Hinweise',requests:'RP-Gesuche',plots:'Plotgruppen',stock:'Lager & Materialien',access:'RP-Ränge & Rechte',publicSettings:'Öffentliche Seiten',settings:'Meine Einstellungen'};
  const live=(ctx,e)=>!ctx.disposed&&ctx.epoch===e;
  const field=(label,type='text',value='',options=[])=>{const wrap=el('label','form-field',label),input=el(type==='textarea'?'textarea':type==='select'?'select':'input','');if(input.tagName==='INPUT')input.type=type;if(type==='select')options.forEach(([value,text])=>{const o=el('option','',text);o.value=value;input.append(o);});if(type==='checkbox')input.checked=!!value;else input.value=value;input.maxLength=type==='textarea'?20000:200;wrap.append(input);return {wrap,input};};
  const failure=e=>e.message?.includes('conflict')?'Inzwischen geändert. Bitte aktualisiere den Bereich.':e.message?.includes('invalid_stock')?'Die Menge ist ungültig oder der Bestand reicht nicht aus.':e.message?.includes('recipients')?'Wähle aktive Mitglieder für diese Freigabe aus.':Raben.errorMessage(e);
  const act=async(ctx,b,fn)=>{const e=ctx.epoch;b.disabled=true;try{await ctx.authorize();if(!live(ctx,e))return;await fn(e);}catch(error){if(live(ctx,e))ctx.report(failure(error),true);}finally{b.disabled=false;}};
  const button=(ctx,label,fn,classes='button outline small-button')=>{const b=el('button',classes,label);b.type='button';b.addEventListener('click',()=>act(ctx,b,fn));return b;};
  const note=text=>el('p','field-note',text);
  const card=(title,text='')=>{const c=el('article','hub-card');c.append(el('h3','',title));if(text)c.append(note(text));return c;};
  const names=(ctx,ids)=>ids.map(id=>RabenIdentity.name(ctx,id,'Ehemaliges Clanmitglied')).join(', ');
  const identity=(ctx,id,prefix='')=>{const p=note('');p.append(RabenIdentity.person(ctx,id,{prefix}));return p;};
  const editor=(ctx,title)=>{if(ctx.dirty&&!confirm('Ungespeicherte Eingaben verwerfen?'))return null;ctx.dirty=false;const f=el('form','hub-editor');f.append(el('h3','',title));f.addEventListener('input',()=>ctx.dirty=true);f.addEventListener('change',()=>ctx.dirty=true);ctx.editor.replaceChildren(f);return f;};
  const submit=(ctx,form,label,fn)=>{const b=el('button','button small-button',label);b.type='submit';form.append(b,button(ctx,'Schließen',()=>{if(!ctx.dirty||confirm('Ungespeicherte Eingaben verwerfen?')){ctx.dirty=false;ctx.editor.replaceChildren();}}));form.addEventListener('submit',e=>{e.preventDefault();act(ctx,b,async epoch=>{await fn(epoch);});});return b;};
  const pickMembers=(ctx,selected=[])=>{const area=el('fieldset','profile-recipients');area.append(el('legend','','Teilnehmende auswählen'));const inputs=[];for(const person of ctx.identities?.values()||[]){if(person.user_id===ctx.actor.user_id)continue;const f=field(person.display_name,'checkbox',selected.includes(person.user_id));f.input.value=person.user_id;inputs.push(f.input);area.append(f.wrap);}return {wrap:area,read:()=>inputs.filter(i=>i.checked).map(i=>i.value)};};
  const characters=async(ctx,form,existing=null)=>{
    const f=field('Als eigener Charakter schreiben','select','',[['','Mit Kontonamen']]);form.append(f.wrap,note('Bei einem ausgewählten Charakter wird dessen Name in diesem Beitrag festgehalten. Freigegebene Charakterinfos werden dadurch nicht erweitert.'));
    const rows=await check(Raben.client().from('raben_profile_items').select('id,title').eq('owner_id',ctx.actor.user_id).eq('kind','character').order('title'));
    rows.forEach(row=>{const o=el('option','',row.title);o.value=row.id;f.input.append(o);});
    if(existing?.speakerId&&!rows.some(r=>r.id===existing.speakerId)){const o=el('option','',existing.speakerName||'Bisheriger Charakter');o.value=existing.speakerId;f.input.append(o);}f.input.value=existing?.speakerId||'';
    return {read:()=>f.input.value?{speakerId:f.input.value}: {},name:()=>rows.find(r=>r.id===f.input.value)?.title||existing?.speakerName||'',input:f.input};
  };
  const recordEditor=(ctx,row,grid)=>{
    const audience=field('RP-Ebene','select',row?.details?.audience||'mixed',[['ic','IC · in der Rolle'],['ooc','OOC · Organisation'],['mixed','IC und OOC']]);grid.append(audience.wrap);let speaker;
    const promise=characters(ctx,grid,row?.details).then(value=>speaker=value);
    const calendar=row?.kind==='event'?RabenCalendar.editor(grid,row.details||{},field):null;
    return {read:async()=>{await promise;const data={audience:audience.input.value,speakerId:'',...speaker.read()};if(calendar)Object.assign(data,calendar.read());return data;}};
  };
  const marker=(row,card)=>{const d=row.details||row;if(d.audience)card.append(el('span','hub-badge',({ic:'IC',ooc:'OOC',mixed:'IC / OOC'}[d.audience])));if(d.speakerName||d.speaker_name)card.append(note('Geschrieben als '+(d.speakerName||d.speaker_name)));};
  const comments=(ctx,type,id,host,owner)=>{
    window.RabenInteractions?.like(ctx,type,id,host);
    const epoch=ctx.epoch,details=el('details','clan-discussion');details.append(el('summary','','Antworten & Reaktionen'));const area=el('div','');details.append(area);host.append(details);let opened=false;
    const draw=async()=>{
      await ctx.authorize();const [rows,reactions]=await Promise.all([check(Raben.client().from('raben_comments').select('id,created_by,body,revision,created_at').eq('parent_type',type).eq('parent_id',id).order('created_at').limit(100)),check(Raben.client().from('raben_reactions').select('user_id,emoji').eq('parent_type',type).eq('parent_id',id))]);
      if(!live(ctx,epoch)||!details.isConnected)return;area.replaceChildren();const reactionBar=el('div','hub-inline-actions');[['raven','🐦‍⬛'],['heart','♥']].forEach(([emoji,label])=>{
        const mine=reactions.some(r=>r.user_id===ctx.actor.user_id&&r.emoji===emoji),b=button(ctx,label+' '+reactions.filter(r=>r.emoji===emoji).length,async()=>{let q=Raben.client().from('raben_reactions');q=mine?q.delete().eq('parent_type',type).eq('parent_id',id).eq('user_id',ctx.actor.user_id).eq('emoji',emoji):q.insert({parent_type:type,parent_id:id,emoji});await check(q);await draw();});b.setAttribute('aria-pressed',String(mine));reactionBar.append(b);});area.append(reactionBar);
      rows.forEach(row=>{const comment=el('article','clan-comment');comment.append(identity(ctx,row.created_by),el('p','hub-body',row.body));
        if(row.created_by===ctx.actor.user_id)comment.append(button(ctx,'Antwort bearbeiten',()=>{const form=editor(ctx,'Antwort bearbeiten');if(!form)return;const body=field('Antwort','textarea',row.body);body.input.required=true;body.input.maxLength=4000;form.append(body.wrap);submit(ctx,form,'Speichern',async()=>{const changed=await check(Raben.client().from('raben_comments').update({body:body.input.value.trim()}).eq('id',row.id).eq('revision',row.revision).select('id'));if(!changed.length)throw new Error('comment_conflict');ctx.dirty=false;ctx.editor.replaceChildren();await draw();});}));
        if(row.created_by===ctx.actor.user_id||(['record','post','request'].includes(type)&&ctx.actor.role==='admin')||(owner===ctx.actor.user_id&&['plot','profile','portrait','profile_image'].includes(type)))comment.append(button(ctx,'Antwort löschen',async()=>{if(!confirm('Diese Antwort löschen?'))return;await check(Raben.client().from('raben_comments').delete().eq('id',row.id).eq('revision',row.revision));await draw();}));area.append(comment);
      });if(rows.length===100)area.append(note('Es werden die ersten 100 Antworten gezeigt.'));
      const form=el('form','comment-form'),body=field('Deine Antwort','textarea');body.input.required=true;body.input.maxLength=4000;form.append(body.wrap);const mentions=el('details','');mentions.append(el('summary','','Mitglieder erwähnen'));const picker=pickMembers(ctx);mentions.append(picker.wrap);form.append(mentions);const send=el('button','button outline small-button','Antwort senden');send.type='submit';form.append(send);form.addEventListener('submit',e=>{e.preventDefault();act(ctx,send,async()=>{const ids=picker.read();if(ids.length>10)throw new Error('invalid_mentions');await check(Raben.client().from('raben_comments').insert({parent_type:type,parent_id:id,body:body.input.value.trim(),mentions:ids}));await draw();});});area.append(form);
    };details.addEventListener('toggle',()=>{if(details.open&&!opened){opened=true;draw().catch(e=>{opened=false;ctx.report(failure(e),true);});}});
  };
  const openParent=async(ctx,type,id)=>{
    if(type==='record'){const rows=await check(Raben.client().from('raben_records').select('id,kind').eq('id',id).limit(1));if(rows[0])ctx.openRecord(rows[0]);else ctx.report('Dieser Eintrag ist nicht mehr für dich freigegeben.');}
    else if(type==='post'){const node=document.querySelector('[data-post-id="'+id+'"]');if(node)node.scrollIntoView({block:'center'});else location.href=new URL('clan.html#post-'+id,Raben.config.siteUrl).href;}
    else {ctx.expandedTarget=id;ctx.navigate(type==='plot'?'plots':'requests');}
  };
  const home=async ctx=>{
    const e=ctx.epoch;const [posts,records,own,claims]=await Promise.all([check(Raben.client().from('raben_clan_posts').select('id,title,body,created_by,created_at').order('created_at',{ascending:false}).limit(3)),check(Raben.client().from('raben_records').select('id,kind,title,details').in('kind',['event','task']).in('visibility',['clan','public']).limit(100)),check(Raben.client().from('raben_profile_items').select('id,title').eq('owner_id',ctx.actor.user_id).eq('kind','character')),check(Raben.client().from('raben_task_claims').select('record_id,state'))]);if(!live(ctx,e))return;
    const greeting=card('Willkommen, '+RabenIdentity.name(ctx,ctx.actor.user_id,ctx.actor.display_name), 'Deine Termine, Aufgaben und Charaktere an einem Ort.');greeting.append(button(ctx,'Mein Profil',()=>{ctx.profileId=ctx.actor.user_id;ctx.navigate('profiles');}),button(ctx,'RP für heute suchen',()=>ctx.navigate('requests')));ctx.list.append(greeting);
    const events=records.filter(r=>r.kind==='event'&&!r.details.cancelled).map(r=>({...r,next:RabenCalendar.dates(r.details,RabenCalendar.day(),1)[0]})).filter(r=>r.next).sort((a,b)=>a.next.localeCompare(b.next));const next=events[0],event=card('Nächster RP-Termin',next?next.next+' · '+next.title:'Noch kein bevorstehender Termin.');if(next)event.append(button(ctx,'Termin öffnen',()=>ctx.openRecord(next)));ctx.list.append(event);
    const notices=card('Neue Aushänge');posts.forEach(post=>notices.append(button(ctx,post.title,()=>openParent(ctx,'post',post.id)),identity(ctx,post.created_by)));if(!posts.length)notices.append(note('Noch keine Aushänge.'));ctx.list.append(notices);
    const tasks=card('Offene Aufträge');records.filter(r=>r.kind==='task'&&!claims.some(c=>c.record_id===r.id&&c.state==='done')).slice(0,5).forEach(r=>tasks.append(button(ctx,r.title,()=>ctx.openRecord(r))));if(tasks.childNodes.length===1)tasks.append(note('Alle Aufträge sind erledigt oder es gibt noch keine.'));ctx.list.append(tasks);
    const character=card('Meine Charaktere',own.length?own.map(c=>c.title).join(' · '):'Lege deinen ersten Charakter im Clanprofil an.');character.append(button(ctx,'Charaktere pflegen',()=>{ctx.profileId=ctx.actor.user_id;ctx.navigate('profiles');}));ctx.list.append(character);
    const recent=card('Zuletzt besucht');for(const kind of recentKinds(ctx))if(kind!==ctx.kind&&(labels[kind]||ctx.recordLabels?.[kind]))recent.append(button(ctx,labels[kind]||ctx.describe(kind),()=>ctx.navigate(kind)));ctx.list.append(recent);
  };
  const searchAll=async ctx=>{
    const epoch=ctx.epoch,form=el('form','hub-search'),query=field('Im Clan suchen','search',ctx.searchAllTerm||''),scope=field('Bereich','select',ctx.searchAllScope||'all',[['all','Alle sichtbaren Inhalte'],['record','Beiträge, Wissen, Medien, Termine'],['profile','Clanprofile'],['character','Persönliche Charaktere'],['plot','Meine freigegebenen Plots'],['request','RP-Gesuche']]);query.input.maxLength=100;query.input.required=true;form.append(query.wrap,scope.wrap);const result=el('div','hub-list'),find=el('button','button small-button','Suchen'),more=button(ctx,'Weitere Ergebnisse',()=>load(false));find.type='submit';form.append(find);more.hidden=true;ctx.list.append(form,result,more);let offset=0,run=0;
    const load=async reset=>{const attempt=++run;if(reset){offset=0;result.replaceChildren();}const rows=await check(Raben.client().rpc('raben_search',{p_query:query.input.value.trim(),p_scope:scope.input.value,p_offset:offset}));if(!live(ctx,epoch)||attempt!==run)return;ctx.searchAllTerm=query.input.value;ctx.searchAllScope=scope.input.value;if(!rows.length&&!offset)result.append(note('Keine für dich sichtbaren Treffer.'));
      rows.forEach(row=>{const c=card(row.title,row.snippet);c.append(button(ctx,'Öffnen',()=>{if(row.type==='profile'||row.type==='character'){ctx.profileId=row.owner_id;ctx.navigate('profiles');}else openParent(ctx,row.type,row.id);}));result.append(c);});offset+=rows.length;more.hidden=rows.length<25;};
    form.addEventListener('submit',e=>{e.preventDefault();act(ctx,find,()=>load(true));});if(query.input.value)await load(true);
  };
  const notices=async ctx=>{const epoch=ctx.epoch;const rows=await check(Raben.client().from('raben_notifications').select('id,label,parent_type,parent_id,created_at,read_at').order('created_at',{ascending:false}).limit(100));if(!live(ctx,epoch))return;ctx.list.append(button(ctx,'Hinweis-Einstellungen',()=>ctx.navigate('settings')));if(!rows.length)ctx.list.append(card('Keine neuen Hinweise','Nur Hinweise zu weiterhin freigegebenen Inhalten werden angezeigt.'));
    rows.forEach(row=>{const c=card(row.read_at?'Gelesen':'Neu',row.label+' · '+new Date(row.created_at).toLocaleString('de-DE'));c.append(button(ctx,'Öffnen',async()=>{await check(Raben.client().from('raben_notifications').update({read_at:new Date().toISOString()}).eq('id',row.id));await openParent(ctx,row.parent_type,row.parent_id);}),button(ctx,'Entfernen',async()=>{await check(Raben.client().from('raben_notifications').delete().eq('id',row.id));c.remove();await bell(ctx);}));ctx.list.append(c);});await bell(ctx);
  };
  const bell=async ctx=>{if(ctx.public||ctx.disposed)return;const e=ctx.epoch,r=await Raben.client().from('raben_notifications').select('id',{count:'exact',head:true}).is('read_at',null);if(r.error)throw r.error;if(!live(ctx,e))return;const tab=ctx.tabs.find(t=>t.dataset.kind==='notices');if(tab)tab.textContent='🔔 Hinweise'+(r.count?' ('+r.count+')':'');if(ctx.notificationButton)ctx.notificationButton.textContent='🔔 '+(r.count||0);};
  const requests=async ctx=>{
    const e=ctx.epoch,rows=await check(Raben.client().from('raben_rp_requests').select('*').order('starts_at').limit(100));if(!live(ctx,e))return;ctx.list.append(button(ctx,'RP-Gesuch erstellen',()=>requestEditor(ctx)));
    if(!rows.length)ctx.list.append(card('Wer spielt heute?','Erstelle ein Gesuch mit Charakter und gewünschter Spielzeit. Abgelaufene Gesuche verschwinden für andere Mitglieder automatisch.'));
    rows.forEach(row=>{const c=card(row.title,row.body);c.dataset.expansionId=row.id;c.append(identity(ctx,row.created_by),note(new Date(row.starts_at).toLocaleString('de-DE')+(row.character_name?' · '+row.character_name:'')),note(row.closed?'Geschlossen':'Gültig bis '+new Date(row.expires_at).toLocaleString('de-DE')));
      if(row.created_by===ctx.actor.user_id)c.append(button(ctx,'Bearbeiten',()=>requestEditor(ctx,row)));if(row.created_by===ctx.actor.user_id||ctx.actor.role==='admin')c.append(button(ctx,'Löschen',async()=>{if(confirm('Dieses RP-Gesuch löschen?')){await check(Raben.client().from('raben_rp_requests').delete().eq('id',row.id).eq('revision',row.revision));await mount(ctx);}}));comments(ctx,'request',row.id,c,row.created_by);ctx.list.append(c);});
  };
  const requestEditor=async(ctx,row=null)=>{
    const f=editor(ctx,row?'Gesuch bearbeiten':'RP-Gesuch erstellen');if(!f)return;const title=field('Titel','text',row?.title||'Wer spielt heute?'),body=field('Gesuch','textarea',row?.body||''),start=field('Gewünschte Spielzeit','datetime-local',row?.starts_at?localDate(row.starts_at):localDate(new Date().toISOString())),expiry=field('Gültig bis','datetime-local',row?.expires_at?localDate(row.expires_at):localDate(new Date(Date.now()+24*3600000).toISOString())),closed=field('Gesuch schließen','checkbox',row?.closed);title.input.required=true;body.input.maxLength=8000;start.input.required=true;expiry.input.required=true;f.append(title.wrap,body.wrap,start.wrap,expiry.wrap,closed.wrap);const speaker=await characters(ctx,f,{speakerName:row?.character_name});submit(ctx,f,'Gesuch speichern',async()=>{const data={title:title.input.value.trim(),body:body.input.value.trim(),starts_at:new Date(start.input.value).toISOString(),expires_at:new Date(expiry.input.value).toISOString(),closed:closed.input.checked,character_name:speaker.name()};const q=Raben.client().from('raben_rp_requests'),result=row?await check(q.update(data).eq('id',row.id).eq('revision',row.revision).select('id')):await check(q.insert(data).select('id'));if(!result.length)throw new Error('request_conflict');ctx.dirty=false;await mount(ctx);});
  };
  const localDate=value=>{const d=new Date(value);return new Date(d-d.getTimezoneOffset()*60000).toISOString().slice(0,16);};
  const plots=async ctx=>{
    const e=ctx.epoch,rows=await check(Raben.client().from('raben_plots').select('*').order('updated_at',{ascending:false}).limit(100));if(!live(ctx,e))return;ctx.list.append(button(ctx,'Plotgruppe anlegen',()=>plotEditor(ctx)));
    if(!rows.length)ctx.list.append(card('Gemeinsame Handlungsfäden','Plane Szenen, halte offene Fragen und Ergebnisse fest. Eine Plotgruppe ist für dich, ausgewählte Mitglieder oder den Clan sichtbar.'));
    rows.forEach(row=>{const c=card(row.title,row.body);c.dataset.expansionId=row.id;c.append(identity(ctx,row.owner_id,'Plotführung: '),note(({private:'Nur ich',selected:'Ausgewählte Mitglieder',clan:'Clan'}[row.visibility])+' · '+({planning:'In Planung',active:'Laufend',finished:'Abgeschlossen'}[row.stage])));
      row.chapters.forEach((chapter,index)=>{const d=el('details','');d.append(el('summary','',String(index+1)+'. '+chapter.title));for(const [key,label] of [['body','Kapitel'],['nextScene','Nächste Szene / offene Fäden'],['result','Ergebnis / Spielbericht']])if(chapter[key])d.append(el('p','hub-body',label+'\n'+chapter[key]));c.append(d);});
      if(row.owner_id===ctx.actor.user_id)c.append(button(ctx,'Plot bearbeiten',()=>plotEditor(ctx,row)),button(ctx,'Plot löschen',async()=>{if(confirm('Plotgruppe mit Kapiteln und Freigaben löschen?')){await check(Raben.client().from('raben_plots').delete().eq('id',row.id).eq('revision',row.revision));await mount(ctx);}}));comments(ctx,'plot',row.id,c,row.owner_id);ctx.list.append(c);
    });
  };
  const plotEditor=async(ctx,row=null)=>{
    const f=editor(ctx,row?'Plotgruppe bearbeiten':'Plotgruppe anlegen');if(!f)return;const title=field('Titel','text',row?.title||''),body=field('Hintergrund','textarea',row?.body||''),visibility=field('Sichtbarkeit','select',row?.visibility||'selected',[['private','Nur ich'],['selected','Ausgewählte Mitglieder'],['clan','Ganzer Clan']]),stage=field('Stand','select',row?.stage||'planning',[['planning','Planung'],['active','Laufend'],['finished','Abgeschlossen']]);title.input.required=true;const grants=row?await check(Raben.client().from('raben_plot_guests').select('user_id').eq('plot_id',row.id)):[],picker=pickMembers(ctx,grants.map(g=>g.user_id));f.append(title.wrap,body.wrap,visibility.wrap,stage.wrap,picker.wrap);const toggle=()=>picker.wrap.hidden=visibility.input.value!=='selected';visibility.input.addEventListener('change',toggle);toggle();
    const chapters=el('div',''),inputs=[];const add=(value={})=>{if(inputs.length>=40)return;const section=el('fieldset','');section.append(el('legend','','Kapitel '+(inputs.length+1)));const fields={};[['title','Titel'],['body','Kapitel / Plan'],['nextScene','Nächste Szene / offene Fäden'],['result','Ergebnis / Spielbericht']].forEach(([key,label])=>{const x=field(label,key==='title'?'text':'textarea',value[key]||'');x.input.maxLength=key==='title'?200:key==='nextScene'?2000:10000;fields[key]=x.input;section.append(x.wrap);});const remove=field('Dieses Kapitel entfernen','checkbox');section.append(remove.wrap);inputs.push({fields,remove:remove.input});chapters.append(section);};(row?.chapters||[{}]).forEach(add);f.append(chapters,button(ctx,'Kapitel ergänzen',()=>{add();ctx.dirty=true;}));
    submit(ctx,f,'Plot speichern',async()=>{const chapters=inputs.filter(c=>!c.remove.checked).map(c=>Object.fromEntries(Object.entries(c.fields).map(([key,input])=>[key,input.value.trim()]))).filter(c=>c.title);await check(Raben.client().rpc('raben_save_plot',{p_id:row?.id||null,p_title:title.input.value.trim(),p_body:body.input.value.trim(),p_visibility:visibility.input.value,p_stage:stage.input.value,p_chapters:chapters,p_guests:picker.read(),p_expected:row?.revision??null}));ctx.dirty=false;await mount(ctx);});
  };
  const stock=async ctx=>{
    const e=ctx.epoch,[items,projects,moves,needs]=await Promise.all([check(Raben.client().from('raben_stock_items').select('*').order('name')),check(Raben.client().from('raben_records').select('id,title').eq('kind','project').in('visibility',['clan','public'])),check(Raben.client().from('raben_stock_movements').select('*').order('created_at',{ascending:false}).limit(100)),check(Raben.client().from('raben_project_materials').select('*'))]);if(!live(ctx,e))return;
    ctx.list.append(card('Gemeinsamer Lagerbestand','Bestände werden von euch eingetragen. Jede Ein- und Auslagerung bekommt eine Menge, einen Grund und optional ein Bauprojekt.'));
    ctx.list.append(button(ctx,'Material anlegen',()=>{const f=editor(ctx,'Material anlegen');if(!f)return;const name=field('Material'),unit=field('Einheit','text','Stück');name.input.required=true;unit.input.required=true;unit.input.maxLength=30;f.append(name.wrap,unit.wrap);submit(ctx,f,'Material speichern',async()=>{await check(Raben.client().from('raben_stock_items').insert({name:name.input.value.trim(),unit:unit.input.value.trim()}));ctx.dirty=false;await mount(ctx);});}));
    items.forEach(item=>{const c=card(item.name,item.quantity+' '+item.unit);c.append(button(ctx,'Ein- oder auslagern',()=>{const f=editor(ctx,item.name+' · Lagerbewegung');if(!f)return;const quantity=field('Menge · positiv einlagern, negativ auslagern','number'),reason=field('Grund'),project=field('Bauprojekt, optional','select','',[['','Ohne Projekt'],...projects.map(p=>[p.id,p.title])]);quantity.input.step='.001';quantity.input.required=true;reason.input.required=true;reason.input.maxLength=500;f.append(quantity.wrap,reason.wrap,project.wrap);submit(ctx,f,'Bewegung buchen',async()=>{await check(Raben.client().rpc('raben_move_stock',{p_item:item.id,p_delta:Number(quantity.input.value),p_reason:reason.input.value.trim(),p_project:project.input.value||null,p_expected:item.revision}));ctx.dirty=false;await mount(ctx);});}));ctx.list.append(c);});
    projects.forEach(project=>{const c=card('Materialbedarf · '+project.title);needs.filter(n=>n.project_id===project.id).forEach(n=>{const item=items.find(i=>i.id===n.item_id);if(item)c.append(note(item.name+': '+n.required+' '+item.unit+' benötigt · '+item.quantity+' im Lager · '+Math.max(0,Number(n.required)-Number(item.quantity))+' fehlen'));if(ctx.capabilities?.content)c.append(button(ctx,'Bedarf entfernen',async()=>{await check(Raben.client().from('raben_project_materials').delete().eq('project_id',project.id).eq('item_id',n.item_id));await mount(ctx);}));});
      if(ctx.capabilities?.content)c.append(button(ctx,'Materialbedarf ergänzen',()=>{const f=editor(ctx,project.title+' · Materialbedarf');if(!f)return;const item=field('Material','select','',items.map(i=>[i.id,i.name+' · '+i.unit])),quantity=field('Benötigte Gesamtmenge','number');quantity.input.required=true;quantity.input.min='.001';quantity.input.step='.001';f.append(item.wrap,quantity.wrap);submit(ctx,f,'Bedarf speichern',async()=>{await check(Raben.client().from('raben_project_materials').upsert({project_id:project.id,item_id:item.input.value,required:Number(quantity.input.value)},{onConflict:'project_id,item_id'}));ctx.dirty=false;await mount(ctx);});}));ctx.list.append(c);
    });const ledger=card('Letzte Lagerbewegungen');moves.forEach(m=>{const item=items.find(i=>i.id===m.item_id),p=note((Number(m.delta)>0?'+':'')+m.delta+' '+(item?.unit||'')+' '+(item?.name||'Material')+' · '+m.reason+' · '+new Date(m.created_at).toLocaleString('de-DE'));p.append(RabenIdentity.person(ctx,m.created_by,{prefix:' · '}));ledger.append(p);});ctx.list.append(ledger);
  };
  const publicSettings=async ctx=>{if(ctx.actor.role!=='admin')throw {code:'42501'};const epoch=ctx.epoch,row=await check(Raben.client().from('raben_site_content').select('content,revision').eq('id',1).single());if(!live(ctx,epoch))return;const f=el('form','hub-editor'),inputs={};f.append(el('h3','','Öffentliche Vorstellung und Kontakt'),note('Tragt eure tatsächliche Lore, Regeln und Kontaktangaben ein. Leere Felder bleiben auf der öffentlichen Seite als noch ausstehend gekennzeichnet.'));
    [['lore','Dorf und Hintergrund'],['rules','RP-Regeln'],['faq','Häufige Fragen'],['applicationGuide','Bewerbung · Ablauf und Voraussetzungen'],['contact','Kontakt / Clanführung'],['privacy','Datenschutzhinweise'],['legal','Anbieterkennzeichnung, soweit erforderlich']].forEach(([key,label])=>{const x=field(label,'textarea',row.content.publicPages?.[key]||'');x.input.maxLength=15000;inputs[key]=x.input;f.append(x.wrap);});f.addEventListener('input',()=>ctx.dirty=true);submit(ctx,f,'Öffentliche Seiten speichern',async()=>{const publicPages=Object.fromEntries(Object.entries(inputs).map(([key,input])=>[key,input.value.trim()]));const changed=await check(Raben.client().from('raben_site_content').update({content:{...row.content,publicPages}}).eq('id',1).eq('revision',row.revision).select('revision'));if(!changed.length)throw new Error('content_conflict');ctx.dirty=false;await mount(ctx);ctx.report('Öffentliche Seiten gespeichert.');});ctx.list.append(f);const controls=RabenMedia.progressControls();ctx.list.append(controls.wrap,button(ctx,'Vorhandene Hintergrundbilder optimieren',async()=>{const content={...row.content};for(const key of ['heroImage','villageImage']){const url=Raben.imageUrl(content[key]);if(!url)continue;const path=new URL(url).pathname.split('/raben-public/')[1];const blob=await check(Raben.client().storage.from('raben-public').download(decodeURIComponent(path)));const file=new File([blob],path,{type:blob.type});const previews=await RabenPictures.uploadPreviews(ctx,file,controls);content[key+'Small']=previews.small;content[key+'Medium']=previews.medium;}const changed=await check(Raben.client().from('raben_site_content').update({content}).eq('id',1).eq('revision',row.revision).select('revision'));if(!changed.length)throw new Error('content_conflict');ctx.dirty=false;await mount(ctx);ctx.report('Vorhandene Hintergründe optimiert. Die Originale bleiben erhalten.');}));
  };
  const recentKinds=ctx=>{try{return JSON.parse(localStorage.getItem('raben-recent-'+ctx.actor.user_id)||'[]').filter(k=>ctx.tabs.some(t=>t.dataset.kind===k));}catch(_){return [];}};
  const remember=(ctx,kind)=>{if(ctx.public)return;try{localStorage.setItem('raben-recent-'+ctx.actor.user_id,JSON.stringify([kind,...recentKinds(ctx).filter(k=>k!==kind)].slice(0,6)));}catch(_){}};
  const setMotion=disabled=>{try{localStorage.setItem('raben-reduced-motion',disabled?'1':'0');}catch(_){}document.documentElement.classList.toggle('reduce-motion',disabled);window.dispatchEvent(new Event('raben-motion-changed'));};
  const navigation=ctx=>{
    if(ctx.public)return;const wrap=el('nav','hub-mobile-nav');wrap.setAttribute('aria-label','Schnellzugriff');const select=el('select','');select.setAttribute('aria-label','Clanbereich auswählen');const groups=[['Mein Clan',['home','clanInfo','profiles','notices','settings','searchAll']],['RP und Dorfleben',['requests','plots','event','character','journal','chronicle','stories','place','gallery','media']],['Gemeinsame Arbeit',['task','project','stock','knowledge','poll','trade']],['Verwaltung',['dashboard','applications','review','access','publicSettings','webhook','emblem','history','storage','backup']]];
    groups.forEach(([label,kinds])=>{const group=el('optgroup','');group.label=label;kinds.forEach(kind=>{const tab=ctx.tabs.find(t=>t.dataset.kind===kind);if(tab){const o=el('option','',tab.textContent);o.value=kind;group.append(o);}});if(group.childNodes.length)select.append(group);});select.addEventListener('change',()=>ctx.navigate(select.value));wrap.append(select,button(ctx,'⌂ Start',()=>ctx.navigate('home')));ctx.notificationButton=button(ctx,'🔔 Hinweise',()=>ctx.navigate('notices'));wrap.append(ctx.notificationButton,button(ctx,'⌕ Suche',()=>ctx.navigate('searchAll')));ctx.root.prepend(wrap);ctx.kindSelect=select;
  };
  const handlers={home,searchAll,notices,requests,plots,stock,publicSettings};
  const mount=async ctx=>{if(!handlers[ctx.kind]||ctx.public)return;const epoch=++ctx.epoch;RabenMedia.release(ctx);ctx.more.hidden=true;ctx.editor.replaceChildren();ctx.list.replaceChildren();ctx.dirty=false;ctx.report('Wird geladen …');await ctx.authorize();if(!live(ctx,epoch))return;await RabenIdentity.load(ctx);if(!live(ctx,epoch))return;await handlers[ctx.kind](ctx);if(live(ctx,epoch)){ctx.report('');if(ctx.expandedTarget){const c=ctx.list.querySelector('[data-expansion-id="'+ctx.expandedTarget+'"]');c?.scrollIntoView?.({block:'center'});if(c)c.classList.add('target-card');delete ctx.expandedTarget;}}};
  const audit=async ctx=>{await bell(ctx);if(['plots','requests','searchAll','notices','home','stock','access'].includes(ctx.kind)&&!ctx.dirty&&!ctx.editor.childNodes.length){const epoch=ctx.epoch,type=ctx.kind==='plots'?'plot':ctx.kind==='requests'?'request':null;if(type){const rows=await check(Raben.client().from(type==='plot'?'raben_plots':'raben_rp_requests').select('id'));if(!live(ctx,epoch))return;const ids=new Set(rows.map(r=>r.id));for(const node of ctx.list.querySelectorAll('[data-expansion-id]'))if(!ids.has(node.dataset.expansionId)){node.remove();}}if(!ctx.list.querySelector('.clan-discussion[open]'))await mount(ctx);}};
  const rankLabels=async ctx=>{const [ranks,assigned]=await Promise.all([check(Raben.client().from('raben_ranks').select('id,label')),check(Raben.client().from('raben_member_ranks').select('user_id,rank_id'))]);ctx.rankLabels=new Map(assigned.map(a=>[a.user_id,ranks.find(r=>r.id===a.rank_id)?.label||'']));};
  try{document.documentElement.classList.toggle('reduce-motion',localStorage.getItem('raben-reduced-motion')==='1');}catch(_){}
  window.RabenExpansion={labels,handlers,mount,audit,bell,navigation,remember,recordEditor,marker,comments,characters,openParent,rankLabels,field,button};
})();
