(() => {
 'use strict';const {el,check}=Raben;
 const button=(label,fn)=>{const b=el('button','button outline small-button',label);b.type='button';b.addEventListener('click',fn);return b;};
 const map=async(ctx,rows)=>{
  const epoch=ctx.epoch,site=await check(Raben.client().from('raben_site_content').select('content').eq('id',1).single());if(ctx.disposed||ctx.epoch!==epoch)return;
  const viewport=el('div','village-viewport'),stage=el('div','hub-map village-map'),controls=el('div','hub-inline-actions'),selection=el('article','hub-card village-selection');let zoom=1;viewport.tabIndex=0;viewport.setAttribute('aria-label','Dorfplan · mit den Schaltflächen zoomen und mit den Pfeiltasten verschieben');
  const src=Raben.imageUrl(site.content.rabenMapImage);if(src){const img=el('img','');img.src=src;img.alt='Dorfplan der Schwarzen Raben';stage.append(img);}else stage.classList.add('without-background');
  const apply=()=>{stage.style.width=(zoom*100)+'%';stage.style.maxWidth='none';};controls.append(button('Vergrößern',()=>{zoom=Math.min(3,zoom+.25);apply();}),button('Verkleinern',()=>{zoom=Math.max(1,zoom-.25);apply();}),button('Ganze Karte',()=>{zoom=1;apply();viewport.scrollTo?.({left:0,top:0});}));viewport.addEventListener('keydown',event=>{if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(event.key)){event.preventDefault();viewport.scrollBy?.({left:event.key==='ArrowLeft'?-80:event.key==='ArrowRight'?80:0,top:event.key==='ArrowUp'?-80:event.key==='ArrowDown'?80:0});}});
  const show=row=>{selection.replaceChildren(el('h3','',row.title),el('p','hub-body',row.body));if(ctx.public){const a=el('a','button outline small-button','Ort und Geschichten öffnen');a.href=new URL('ort.html?id='+row.id,Raben.config.siteUrl).href;selection.append(a);}else selection.append(button('Ort im Clan öffnen',()=>ctx.openRecord(row)));};
  rows.forEach((row,index)=>{const pin=button(String(index+1),()=>show(row));pin.className='hub-map-pin';pin.style.left=row.details.x+'%';pin.style.top=row.details.y+'%';pin.setAttribute('aria-label',row.title);stage.append(pin);});viewport.append(stage);selection.append(el('p','field-note','Wähle einen Ort auf der Karte.'));ctx.list.prepend(selection);ctx.list.prepend(viewport);ctx.list.prepend(controls);
  if(!src)ctx.list.prepend(el('p','field-note','Der Kartenhintergrund wird noch ergänzt. Die eingetragenen Orte findest du unten.'));
 };
 const page=async()=>{
  const root=document.getElementById('guide-root');if(!root)return;
  try{
   const site=await check(Raben.client().from('raben_site_content').select('content').eq('id',1).single()),pages={lore:'Die Schwarzen Raben sind ein Conan-Exiles-Roleplay-Clan. Unser Dorf liegt im Schnee und verbindet ein nordisches Setting mit Wikinger-RP.',faq:'Wie melde ich mich an? Über dein Discord-Konto.\n\nWer kommt in den Clanbereich? Angenommene und freigegebene Clanmitglieder.\n\nWer sieht mein Profil? Dein Kontoname und Kontobild sind im Clan sichtbar. Charaktere und Infokarten legst du privat an und gibst sie einzeln für den Clan oder ausgewählte Personen frei.',applicationGuide:'Melde dich auf der Bewerbungsseite mit Discord an. Stelle deinen Charakter, deine RP-Wünsche und deine üblichen Spielzeiten vor. Die Clanführung prüft deine Bewerbung. Bei einer Annahme wird dein Clan-Zugang freigegeben.',privacy:'Die Anmeldung läuft über Discord und Supabase. Die Website speichert eure Clanmitgliedschaft sowie selbst eingetragene Profile und RP-Inhalte. Kontoname und Kontobild sind für aktive Clanmitglieder sichtbar. Private und gezielt geteilte Profileinträge sind durch Zugriffsregeln geschützt. Andere Website-Admins erhalten keinen Sonderzugriff auf private persönliche Profile. Öffentliche Beiträge werden durch Admins freigegeben. Im eigenen Profil kannst du deine Freigaben prüfen, deine Daten mit Bildern sichern und dein persönliches Profil löschen. Weitere Angaben zu Verantwortlichen und Datenschutz ergänzt die Clanführung.',...site.content.publicPages};root.replaceChildren();
   if(document.body.dataset.guidePage==='place'){
    const id=new URL(location.href).searchParams.get('id');if(!window.RabenMedia.UUID.test(id||''))throw new Error('invalid_place');
    const rows=await check(Raben.client().from('raben_records').select('id,kind,title,body,details,visibility').eq('id',id).eq('kind','place').eq('visibility','public').limit(1));if(!rows[0]){root.append(el('p','status-message','Dieser Ort ist derzeit nicht öffentlich freigegeben.'));return;}const place=rows[0];document.getElementById('guide-title').textContent=place.title;const card=el('article','hub-card');card.append(el('h2','',place.title),el('p','hub-body',place.body));root.append(card);
    const ctx={public:true,disposed:false,epoch:0,urls:new Set(),list:root};if(place.details.mediaIds?.length)await RabenMedia.references(ctx,place.details.mediaIds,card);
    if(place.details.relatedIds?.length)await RabenMedia.relations(ctx,place.details.relatedIds,card);
    const stories=await check(Raben.client().from('raben_records').select('id,kind,title,body,details,visibility').eq('visibility','public').contains('details',{relatedIds:[id]}).limit(30));stories.forEach(row=>{const c=el('article','hub-card');c.append(el('h3','',row.title),el('p','hub-body',row.body));const a=el('a','button outline small-button','Geschichte öffnen');a.href=new URL('entdecken.html?eintrag='+row.id,Raben.config.siteUrl).href;c.append(a);root.append(c);});return;
   }
   const sections=document.body.dataset.guidePage==='contact'?[['contact','Kontakt'],['privacy','Datenschutzhinweise'],['legal','Anbieterkennzeichnung']]:[['lore','Dorf und Hintergrund'],['rules','RP-Regeln'],['faq','Häufige Fragen'],['applicationGuide','Zu den Raben kommen']];
   sections.forEach(([key,title])=>{const section=el('section','hub-card');section.id=key;section.append(el('h2','',title),el('p','hub-body',pages[key]||'Die Clanführung ergänzt hier die Angaben.'));root.append(section);});
  }catch(e){root.replaceChildren(el('p','status-message','Die aktuellen Angaben konnten nicht geladen werden. Bitte versuche es erneut.'));}
 };
 window.RabenGuide={map,page};if(document.getElementById('guide-root'))page();
})();
