(() => {
 'use strict';const {el,check}=Raben,{live,note,field,button,submit}=RabenQol,original=RabenGuide.map;
 const publicUrl=path=>new URL('/storage/v1/object/public/raben-public/'+path,Raben.config.supabaseUrl).href;
 const readMaps=ctx=>Raben.client().from('raben_maps').select(ctx.public?'id,title,kind,public_path,layers,visibility,revision':'*').order('created_at').order('id').limit(100);
 const display=async(ctx,map,host)=>{const epoch=ctx.epoch,[pins]=await Promise.all([check(Raben.client().from('raben_map_markers').select('*').eq('map_id',map.id).order('id').limit(500))]);const ids=[...new Set(pins.map(p=>p.place_id))],places=ids.length?await check(Raben.client().from('raben_records').select(ctx.public?'id,title,kind,body,details,visibility':'id,title,kind,body,details,visibility,created_by,revision').in('id',ids).eq('kind','place')):[];if(!live(ctx,epoch)||!host.isConnected)return;
  const layers=el('div','map-layer-controls'),mapArea=el('div','qol-map'),image=el('img',''),legend=el('div','qol-map-legend'),choices=new Map();image.alt=map.title+' · '+({world:'Weltkarte',village:'Dorfplan',building:'Gebäudeansicht'}[map.kind]||'Karte');image.loading='lazy';image.addEventListener('load',()=>{if(image.naturalWidth&&image.naturalHeight)mapArea.style.aspectRatio=image.naturalWidth+'/'+image.naturalHeight;});mapArea.append(image);host.replaceChildren(el('h4','',map.title),layers,mapArea,legend);
  const show=()=>{for(const pin of pins){const node=mapArea.querySelector('[data-map-pin="'+pin.id+'"]'),line=legend.querySelector('[data-map-pin="'+pin.id+'"]');if(node)node.hidden=!choices.get(pin.layer)?.checked;if(line)line.hidden=!choices.get(pin.layer)?.checked;}};
  for(const layer of map.layers){const f=field('Ebene: '+layer,'checkbox',true);choices.set(layer,f.input);f.input.addEventListener('change',show);layers.append(f.wrap);}for(const [index,pin] of pins.entries()){const place=places.find(p=>p.id===pin.place_id);if(!place)continue;const open=()=>ctx.public?ctx.openRecord?.(place):RabenExpansion.openParent(ctx,'record',place.id),b=ctx.public?el('button','qol-map-marker',String(index+1)):button(ctx,String(index+1),open);b.type='button';b.className='qol-map-marker';if(ctx.public)b.addEventListener('click',open);b.dataset.mapPin=pin.id;b.style.left=pin.x+'%';b.style.top=pin.y+'%';b.setAttribute('aria-label',place.title+' · '+pin.layer);mapArea.append(b);const line=note((index+1)+'. '+place.title+' · '+pin.layer);line.dataset.mapPin=pin.id;legend.append(line);}show();
  if(ctx.public)image.src=publicUrl(map.public_path);else RabenQol.observe(ctx,mapArea,async()=>{await ctx.authorize();const blob=await check(Raben.client().storage.from('raben-map-media').download(map.image_path));if(!live(ctx,epoch)||!mapArea.isConnected)return;const url=URL.createObjectURL(blob);ctx.urls.add(url);image.src=url;});
 };
 const render=async(ctx,rows=[])=>{const epoch=ctx.epoch,maps=await check(readMaps(ctx));if(!live(ctx,epoch))return;ctx.list.querySelector('[data-qol-maps]')?.remove();if(!maps.length){const host=el('section','qol-panel');host.dataset.qolMaps='';ctx.list.prepend(host);const child=Object.create(ctx);child.list=host;await original(child,rows);return;}const area=el('section','qol-panel');area.dataset.qolMaps='';const choice=field('Kartenansicht','select','legacy',[['legacy','Bisheriger Dorfplan'],...maps.map(m=>[m.id,({world:'Weltkarte',village:'Dorfplan',building:'Gebäude'}[m.kind])+' · '+m.title])]),view=el('div','');area.append(choice.wrap,view);ctx.list.prepend(area);const child=Object.create(ctx);child.list=view;let request=0;const change=async()=>{const n=++request,next=el('div','');next.append(note('Karte wird geladen …'));view.replaceChildren(next);const map=maps.find(m=>m.id===choice.input.value);if(map)await display(ctx,map,next);else{next.replaceChildren();child.list=next;await original(child,rows);}};choice.input.addEventListener('change',()=>change().catch(error=>ctx.report?.(error.message||Raben.errorMessage(error),true)));await change();};
 const maps=async ctx=>{const epoch=ctx.epoch,rows=await check(readMaps(ctx));ctx.list.append(note('Weltkarte, Dorfplan und Gebäudeansichten haben eigene Ebenen. Blende Kategorien aus, um dich auf bestimmte Orte zu konzentrieren.'));if(rows.length){const choice=field('Karte auswählen','select',rows[0].id,rows.map(m=>[m.id,m.title])),view=el('section','qol-panel');ctx.list.append(choice.wrap,view);const change=()=>{const next=el('div','');view.replaceChildren(next);return display(ctx,rows.find(m=>m.id===choice.input.value),next);};choice.input.addEventListener('change',()=>change().catch(error=>ctx.report(error.message||Raben.errorMessage(error),true)));await change();}else ctx.list.append(note('Noch keine zusätzlichen Karten. Der bisherige Dorfplan bleibt im Bereich „Dorfplan“ verfügbar.'));
  if(ctx.actor.role!=='admin')return;
  const places=await check(Raben.client().from('raben_records').select('id,title,visibility').eq('kind','place').order('title').limit(500));if(!live(ctx,epoch))return;
  const editor=(host,map=null)=>{const f=el('form','qol-grid'),title=field('Kartenname','text',map?.title||''),kind=field('Ansicht','select',map?.kind||'village',[['world','Weltkarte'],['village','Dorfplan'],['building','Gebäudeansicht']]),layers=field('Kartenebenen · eine pro Zeile','textarea',(map?.layers||['Orte']).join('\n')),visibility=field('Sichtbarkeit der Karte','select',map?.visibility||'clan',[['clan','Nur im Clan'],['public','Auf der öffentlichen Website']]),file=field(map?'Kartenbild ersetzen · optional':'Kartenbild hochladen','file',''),progress=RabenMedia.progressControls();title.input.required=true;title.input.maxLength=120;file.input.required=!map;file.input.accept='image/jpeg,image/png,image/webp';f.append(title.wrap,kind.wrap,layers.wrap,visibility.wrap,file.wrap,progress.wrap);submit(ctx,f,map?'Karte speichern':'Karte erstellen',async()=>{let path=map?.image_path,publicPath=map?.public_path||null;const chosen=file.input.files?.[0];if(chosen){const uploaded=await RabenPictures.upload(ctx,chosen,progress,'raben-map-media');path=uploaded.mediumPath||uploaded.imagePath;publicPath=null;}if(!path)throw new Error('Bitte lade ein Kartenbild hoch.');if(visibility.input.value==='public'&&!publicPath){const blob=await check(Raben.client().storage.from('raben-map-media').download(path)),copy=new File([blob],'map.'+path.split('.').pop(),{type:blob.type||'image/webp'});publicPath=await RabenMedia.upload(ctx,copy,ctx.actor.user_id,progress,false,crypto.randomUUID()+'.'+path.split('.').pop(),'raben-public');}const data={title:title.input.value.trim(),kind:kind.input.value,layers:layers.input.value.split('\n').map(s=>s.trim()).filter(Boolean),visibility:visibility.input.value,image_path:path,public_path:publicPath},changed=await check(map?Raben.client().from('raben_maps').update(data).eq('id',map.id).eq('revision',map.revision).select('id'):Raben.client().from('raben_maps').insert(data).select('id'));if(!changed.length)throw new Error('Inzwischen geändert. Bitte aktualisieren.');await RabenQol.reload(ctx);});host.append(f);};const create=el('details','qol-panel');create.append(el('summary','','Neue Karte anlegen'));editor(create);ctx.list.append(create);
  for(const map of rows){const area=el('details','qol-panel');area.append(el('summary','','Verwalten: '+map.title));editor(area,map);const pins=await check(Raben.client().from('raben_map_markers').select('*').eq('map_id',map.id).order('id')),f=el('form','qol-grid'),place=field('Ort auf der Karte','select','',[['','Ort wählen'],...places.filter(p=>map.visibility!=='public'||p.visibility==='public').map(p=>[p.id,p.title])]),layer=field('Ebene des Ortes','select',map.layers[0],map.layers.map(l=>[l,l])),x=field('Position von links in Prozent','number',50),y=field('Position von oben in Prozent','number',50);for(const input of [x.input,y.input]){input.min=0;input.max=100;input.step=.1;input.required=true;}place.input.required=true;f.append(place.wrap,layer.wrap,x.wrap,y.wrap);submit(ctx,f,'Ort zur Karte hinzufügen',async()=>{await check(Raben.client().from('raben_map_markers').insert({map_id:map.id,place_id:place.input.value,layer:layer.input.value,x:Number(x.input.value),y:Number(y.input.value)}));await RabenQol.reload(ctx);});area.append(f);for(const pin of pins){const p=note((places.find(p=>p.id===pin.place_id)?.title||'Ort')+' · '+pin.layer+' · '+pin.x+' / '+pin.y+' %');p.append(button(ctx,'Markierung entfernen',async()=>{await check(Raben.client().from('raben_map_markers').delete().eq('id',pin.id));await RabenQol.reload(ctx);}));area.append(p);}area.append(button(ctx,'Karte löschen',async()=>{if(!confirm('Diese Karte und ihre Markierungen löschen? Die Orte bleiben erhalten.'))return;await check(Raben.client().from('raben_maps').delete().eq('id',map.id).eq('revision',map.revision));await RabenQol.reload(ctx);}));ctx.list.append(area);}
 };
 Object.assign(RabenExpansion.labels,{maps:'Karten & Ebenen'});Object.assign(RabenExpansion.handlers,{maps});RabenGuide.map=render;window.RabenMaps={render,maps,display};
})();
