(() => {
  'use strict';const {el,check}=Raben,B='raben-profile-media';
  const labels={race:'Volk',age:'Alter',origin:'Herkunft',appearance:'Aussehen',skills:'Fähigkeiten',goals:'Ziele'};
  const live=(ctx,epoch)=>!ctx.disposed&&ctx.epoch===epoch;
  const btn=(text,fn)=>{const b=el('button','button outline small-button',text);b.type='button';b.addEventListener('click',()=>act(ctxFor(b),b,fn));return b;};
  const ctxFor=b=>b._ctx;
  const button=(ctx,text,fn)=>{const b=btn(text,fn);b._ctx=ctx;return b;};
  const act=async(ctx,b,fn)=>{b.disabled=true;const epoch=ctx.epoch;try{await ctx.authorize();await fn(epoch);}catch(e){if(live(ctx,epoch))ctx.report(e.message?.includes('conflict')?'Inzwischen geändert. Aktualisiere das Profil.':Raben.errorMessage(e),true);}finally{b.disabled=false;}};
  const field=(label,type='text',value='')=>{const wrap=el('label','form-field',label),input=el(type==='textarea'?'textarea':type==='select'?'select':'input','');if(input.tagName==='INPUT')input.type=type;input.value=value;wrap.append(input);return {wrap,input};};
  const prepare=async(ctx,kind,item,form)=>{
    if(kind!=='character')return null;const epoch=ctx.epoch,inputs={},section=el('fieldset','profile-structured');section.append(el('legend','','Charakterdossier'));
    Object.entries(labels).forEach(([key,label])=>{const f=field(label,['appearance','skills','goals'].includes(key)?'textarea':'text',item?.details?.[key]||'');f.input.maxLength=4000;inputs[key]=f.input;section.append(f.wrap);});
    const custom=el('div',''),pairs=[];const addPair=(value={})=>{if(pairs.length>=12)return;const row=el('div','form-grid'),label=field('Eigenes Feld','text',value.label||''),text=field('Inhalt','textarea',value.value||'');label.input.maxLength=100;text.input.maxLength=4000;row.append(label.wrap,text.wrap);custom.append(row);pairs.push([label.input,text.input]);};
    (item?.details?.custom||[]).forEach(addPair);section.append(custom,button(ctx,'Eigenes Feld ergänzen',()=>addPair()),el('p','field-note','Diese Felder teilen die Sichtbarkeit des Charaktereintrags. Angaben mit anderen Freigaben legst du als eigene Infokarte an.'));
    const existing=item?await check(Raben.client().from('raben_profile_gallery').select('id,image_path,preview_path,caption,display_title,sort_order').eq('item_id',item.id).order('sort_order')):[];if(!live(ctx,epoch))return null;
    const gallery=el('div',''),removed=new Set();existing.forEach(image=>{const p=el('p','field-note',image.display_title||'Charakterbild');p.append(button(ctx,'Aus Galerie entfernen',()=>{removed.add(image.id);p.hidden=true;ctx.dirty=true;}));gallery.append(p);});
    const files=field('Zusätzliche Charakterbilder · insgesamt höchstens 12','file');files.input.multiple=true;files.input.accept='image/jpeg,image/png,image/webp';section.append(gallery,files.wrap);form.append(section);const design=await window.RabenProfileDesign?.prepare(ctx,item,form);
    return {collect:async(data,controls)=>{
      const details={};Object.entries(inputs).forEach(([key,input])=>{if(input.value.trim())details[key]=input.value.trim();});details.custom=pairs.filter(([a])=>a.value.trim()).map(([a,b])=>({label:a.value.trim(),value:b.value.trim()}));
      const images=existing.filter(i=>!removed.has(i.id));if(images.length+(files.input.files?.length||0)>12)throw new Error('gallery_limit');
      for(const file of Array.from(files.input.files||[])){const result=await RabenPictures.upload(ctx,file,controls,B);images.push({image_path:result.imagePath,preview_path:result.thumbPath,caption:'',display_title:''});}
      return {...data,p_details:details,p_gallery:images.map((i,n)=>({id:i.id,image_path:i.image_path,preview_path:i.preview_path,caption:i.caption||'',display_title:i.display_title||'',sort_order:n})),...(design?{p_design:await design.collect(controls)}:{})};
    }};
  };
  const protectedImage=async(ctx,path,host,alt)=>{const epoch=ctx.epoch;try{const blob=await check(Raben.client().storage.from(B).download(path));if(!live(ctx,epoch)||!host.isConnected)return;const url=URL.createObjectURL(blob);ctx.urls.add(url);const image=el('img','hub-image');image.src=url;image.alt=alt;image.loading='lazy';host.append(image);}catch(_){}};
  const render=async(ctx,item,card)=>{
    if(item.kind!=='character')return;const epoch=ctx.epoch,dl=el('dl','character-fields');Object.entries(labels).forEach(([key,label])=>{if(item.details?.[key])dl.append(el('dt','',label),el('dd','hub-body',item.details[key]));});(item.details?.custom||[]).forEach(p=>dl.append(el('dt','',p.label),el('dd','hub-body',p.value)));if(dl.childNodes.length)card.append(dl);
    const [images,relationships]=await Promise.all([check(Raben.client().from('raben_profile_gallery').select('id,image_path,preview_path,display_title,album_id,sort_order').eq('item_id',item.id).order('sort_order')),check(Raben.client().from('raben_relationships').select('*').or('source_id.eq.'+item.id+',target_id.eq.'+item.id).order('created_at'))]);if(!live(ctx,epoch)||!card.isConnected)return;
    const gallery=el('div','character-gallery');card.append(gallery);images.forEach(i=>gallery.append(RabenGallery.figure(ctx,i,item)));await window.RabenProfilePlus?.albums(ctx,item,images,gallery,card);
    const area=el('div','character-relationships');area.append(el('h5','','Bestätigte Beziehungen'));
    for(const relationship of relationships){const ids=[relationship.source_id,relationship.target_id],characters=await check(Raben.client().from('raben_profile_items').select('id,title').in('id',ids));if(!live(ctx,epoch))return;
      if(characters.length!==2)continue;const p=el('p','field-note',characters.find(c=>c.id===relationship.source_id).title+' ↔ '+characters.find(c=>c.id===relationship.target_id).title+' · '+relationship.label+' · '+({pending:'Angefragt',accepted:'Bestätigt',rejected:'Abgelehnt'}[relationship.status]));area.append(p);
      if(relationship.status==='pending'&&relationship.recipient_id===ctx.actor.user_id){for(const [status,label] of [['accepted','Bestätigen'],['rejected','Ablehnen']])p.append(button(ctx,label,async()=>{await check(Raben.client().from('raben_relationships').update({status}).eq('id',relationship.id).eq('status','pending'));ctx.navigate('profiles');}));}
      if(relationship.sender_id===ctx.actor.user_id)p.append(button(ctx,'Zurückziehen',async()=>{await check(Raben.client().from('raben_relationships').delete().eq('id',relationship.id));ctx.navigate('profiles');}));
    }
    if(!relationships.length)area.append(el('p','field-note','Noch keine sichtbaren Beziehungen. Beide Charaktere müssen für die betrachtende Person freigegeben sein.'));
    if(item.owner_id===ctx.actor.user_id){area.append(button(ctx,'Beziehung anfragen',async()=>{
      const choices=await check(Raben.client().from('raben_profile_items').select('id,owner_id,title').eq('kind','character').neq('owner_id',ctx.actor.user_id).order('title'));if(!live(ctx,epoch))return;const form=el('form','hub-editor'),target=field('Anderer Charakter','select'),label=field('Beziehung · zum Beispiel Freundschaft');label.input.required=true;label.input.maxLength=120;
      choices.forEach(c=>{const o=el('option','',c.title+' · '+RabenIdentity.name(ctx,c.owner_id));o.value=c.id;target.input.append(o);});form.append(target.wrap,label.wrap,el('p','field-note','Die andere Person muss deinen Charakter sehen können und bestätigt die Beziehung.'));
      const save=el('button','button small-button','Anfrage senden');save.type='submit';form.append(save);form.addEventListener('input',()=>ctx.dirty=true);form.addEventListener('submit',e=>{e.preventDefault();act(ctx,save,async()=>{const chosen=choices.find(c=>c.id===target.input.value);if(!chosen)throw new Error('character_required');await check(Raben.client().from('raben_relationships').insert({source_id:item.id,target_id:chosen.id,recipient_id:chosen.owner_id,label:label.input.value.trim()}));ctx.dirty=false;ctx.editor.replaceChildren();ctx.navigate('profiles');});});ctx.editor.replaceChildren(form);
    }));}card.append(area);
  };
  const paths=data=>[data.profile?.avatar_path,data.profile?.banner_path,...(data.items||[]).flatMap(i=>[i.image_path,i.preview_path]),...(data.gallery||[]).flatMap(i=>[i.image_path,i.preview_path]),...(data.styles||[]).flatMap(i=>[i.background_path,i.preview_path]),...(data.templates||[]).flatMap(i=>[i.background_path,i.preview_path]),...(data.profileVersions||[]).flatMap(v=>[v.snapshot?.item?.image_path,v.snapshot?.item?.preview_path,...(v.snapshot?.gallery||[]).flatMap(g=>[g.image_path,g.preview_path]),v.snapshot?.design?.background_path,v.snapshot?.design?.preview_path]),...(data.files||[])].filter(Boolean).filter((p,i,a)=>a.indexOf(p)===i);
  const download=(ctx,name,blob)=>{const url=URL.createObjectURL(blob);ctx.urls.add(url);const a=el('a','');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();};
  const controls=(ctx,profile,items)=>{
    const card=el('article','hub-card profile-control');card.append(el('h3','','Deine Daten und Freigaben'),el('p','field-note','Kontoname und Kontobild sind für aktive Clanmitglieder sichtbar. Weitere Angaben bleiben an ihre einzelnen Freigaben gebunden.'));
    const select=field('Vorschau aus Sicht dieses Mitglieds','select');const empty=el('option','','Bitte auswählen');empty.value='';select.input.append(empty);for(const person of ctx.identities?.values()||[]){if(person.user_id===ctx.actor.user_id)continue;const o=el('option','',person.display_name);o.value=person.user_id;select.input.append(o);}const preview=el('div','privacy-preview');card.append(select.wrap,preview);
    select.input.addEventListener('change',async()=>{const epoch=ctx.epoch;try{await ctx.authorize();const grants=await check(Raben.client().from('raben_profile_grants').select('item_id,grantee_id').eq('owner_id',ctx.actor.user_id));if(!live(ctx,epoch))return;preview.replaceChildren();if(!select.input.value)return;preview.append(el('p','field-note','Sichtbar: '+profile.display_name+' und dein Kontobild.'));
      items.forEach(item=>{const visible=item.visibility==='clan'||item.visibility==='selected'&&grants.some(g=>g.item_id===item.id&&g.grantee_id===select.input.value);const p=el('p','field-note',(visible?'Sichtbar: ':'Privat gegenüber dieser Person: ')+item.title);preview.append(p);if(visible){if(item.body)preview.append(el('p','hub-body',item.body));Object.entries(item.details||{}).forEach(([key,value])=>{if(key!=='custom')preview.append(el('p','field-note',(labels[key]||key)+': '+value));});}});
    }catch(e){ctx.report(Raben.errorMessage(e),true);}});
    card.append(button(ctx,'Alle Freigaben prüfen',async epoch=>{const grants=await check(Raben.client().from('raben_profile_grants').select('item_id,grantee_id').eq('owner_id',ctx.actor.user_id));if(!live(ctx,epoch))return;preview.replaceChildren();items.forEach(i=>preview.append(el('p','field-note',i.title+' · '+({private:'Nur ich',clan:'Alle aktiven Mitglieder',selected:grants.filter(g=>g.item_id===i.id).map(g=>RabenIdentity.name(ctx,g.grantee_id,'Nicht aktives Mitglied')).join(', ')}[i.visibility]))));}));
    card.append(button(ctx,'Mein Profil mit Bildern sichern',async epoch=>{const data=await check(Raben.client().rpc('raben_export_profile'));let part=1,total=0,entries={'profile.json':fflate.strToU8(JSON.stringify(data,null,2))};const all=paths(data);const flush=()=>{download(ctx,'mein-rabenprofil-teil-'+part+'.zip',new Blob([fflate.zipSync(entries,{level:0})],{type:'application/zip'}));part++;total=0;entries={'profile.json':fflate.strToU8(JSON.stringify(data,null,2))};};
      for(const path of all){await ctx.authorize();const blob=await check(Raben.client().storage.from(B).download(path));if(!live(ctx,epoch))return;if(total&&total+blob.size>64*1024*1024)flush();entries['files/'+path]=new Uint8Array(await blob.arrayBuffer());total+=blob.size;ctx.report('Profilsicherung: '+Object.keys(entries).length+' Dateien im aktuellen Teil.');}await ctx.authorize();if(live(ctx,epoch)){flush();ctx.report('Persönliche Profilsicherung heruntergeladen.');}
    }));
    card.append(button(ctx,'Eigene unbenutzte Bilder aufräumen',async epoch=>{const data=await check(Raben.client().rpc('raben_export_profile')),used=new Set(paths(data)),area=el('div','');card.append(area);let offset=0;const load=async()=>{const files=await check(Raben.client().storage.from(B).list(ctx.actor.user_id,{limit:100,offset,sortBy:{column:'name',order:'asc'}}));if(!live(ctx,epoch))return;for(const file of files){if(!/^[a-f0-9-]{36}[.](jpg|png|webp)$/.test(file.name))continue;const path=ctx.actor.user_id+'/'+file.name;if(used.has(path))continue;const line=el('p','field-note','Unbenutztes eigenes Bild · '+file.name);line.append(button(ctx,'Datei entfernen',async()=>{if(!confirm('Dieses unbenutzte eigene Bild entfernen?'))return;const removed=await check(Raben.client().storage.from(B).remove([path]));if(!removed?.length)throw new Error('profile_conflict');line.remove();}));area.append(line);}offset+=files.length;if(files.length===100)area.append(button(ctx,'Weitere eigene Dateien prüfen',()=>load()));else if(!area.childNodes.length)area.append(el('p','field-note','Keine unbenutzten eigenen Bilder.'));};await load();}));
    card.append(button(ctx,'Mein persönliches Profil löschen',async epoch=>{const form=el('form','hub-editor'),confirm=field('Zur Bestätigung PROFIL LÖSCHEN eingeben');form.append(el('h3','','Persönliches Profil löschen'),el('p','field-note','Dies löscht Kontoname, Kontobild, Charaktere, Infokarten, Galerien und ihre Freigaben. Dein Discord-Konto und deine Clanmitgliedschaft bleiben bestehen. Bereits geteilte Clanbeiträge bleiben erhalten.'),confirm.wrap);const remove=el('button','button danger small-button','Profil endgültig löschen');remove.type='submit';form.append(remove);form.addEventListener('submit',e=>{e.preventDefault();if(confirm.input.value!=='PROFIL LÖSCHEN')return;act(ctx,remove,async()=>{const data=await check(Raben.client().rpc('raben_export_profile'));const removed=await check(Raben.client().from('raben_profiles').delete().eq('user_id',ctx.actor.user_id).eq('revision',profile.revision).select('user_id'));if(!removed.length)throw new Error('profile_conflict');ctx.dirty=false;for(const path of paths(data)){try{await check(Raben.client().storage.from(B).remove([path]));}catch(_){}}if(!live(ctx,epoch))return;RabenIdentity.changed({user_id:ctx.actor.user_id});ctx.navigate('profiles');ctx.report('Dein Profil wurde gelöscht. Deine Clanmitgliedschaft bleibt bestehen.');});});ctx.editor.replaceChildren(form);confirm.input.focus();}));return card;
  };
  window.RabenProfileTools={prepare,render,controls};
})();
