(() => {
 'use strict';const {el,check}=Raben,{live,note,field,button,submit}=RabenQol;
 const refresh=ctx=>ctx.kind==='profiles'?RabenProfiles.mount(ctx):ctx.reload();
 const coedit=async(ctx,type,row)=>{if(ctx.dirty&&!confirm('Ungespeicherte Eingaben verwerfen?'))return;const f=el('form','hub-editor'),title=field('Titel gemeinsam bearbeiten','text',row.title),body=field('Text gemeinsam bearbeiten','textarea',row.body);title.input.required=true;title.input.maxLength=type==='profile'?120:200;body.input.maxLength=type==='profile'?20000:30000;f.append(el('h3','','Gezielte Mitbearbeitung'),note('Diese Freigabe erlaubt Textänderungen an diesem Eintrag. Bilder, Veröffentlichung und Empfänger legt die besitzende Person fest.'),title.wrap,body.wrap);ctx.editor.replaceChildren(f);let draft;f.addEventListener('input',()=>ctx.dirty=true);submit(ctx,f,'Gemeinsame Texte speichern',async()=>{await check(Raben.client().rpc('raben_coedit_entry',{p_type:type,p_id:row.id,p_title:title.input.value.trim(),p_body:body.input.value.trim(),p_expected:row.revision}));await draft?.clear();ctx.dirty=false;await refresh(ctx);ctx.report('Gemeinsame Texte gespeichert.');});f.append(button(ctx,'Schließen',()=>{if(!ctx.dirty||confirm('Ungespeicherte Eingaben verwerfen?')){ctx.dirty=false;ctx.editor.replaceChildren();}}));draft=await RabenQol.draft(ctx,f,'coedit:'+type+':'+row.id,row.revision);title.input.focus?.();};
 const collaboration=async(ctx,type,row,card)=>{if(ctx.public)return;const epoch=ctx.epoch,owner=row.owner_id||row.created_by,rows=await check(Raben.client().from('raben_entry_editors').select('*').eq('parent_type',type).eq('parent_id',row.id));if(!live(ctx,epoch)||!card.isConnected)return;
  if(owner!==ctx.actor.user_id){if(rows.some(e=>e.editor_id===ctx.actor.user_id&&(!e.expires_at||new Date(e.expires_at)>new Date())))card.append(button(ctx,'Als Mitbearbeiter Texte bearbeiten',()=>coedit(ctx,type,row)));return;}
  if(type==='profile'&&!['character','info'].includes(row.kind))return;
  const area=el('details','qol-panel'),summary=el('summary','','Mitbearbeitung für diesen Eintrag');area.append(summary,note('Nur ausgewählte Mitglieder erhalten Zugriff auf diesen Eintrag und seine Bilder. Du kannst die Freigabe jederzeit entziehen. Allgemeine Adminrechte werden nicht vergeben.'));card.append(area);let loaded=false;
  area.addEventListener('toggle',async()=>{if(!area.open||loaded)return;loaded=true;try{await ctx.authorize();const members=await check(Raben.client().from('raben_memberships').select('user_id,display_name').eq('status','active').order('display_name'));if(!live(ctx,epoch)||!card.isConnected)return;const select=field('Mitglied als Mitbearbeiter','select','',[['','Mitglied auswählen'],...members.filter(m=>m.user_id!==owner&&!rows.some(e=>e.editor_id===m.user_id)).map(m=>[m.user_id,m.display_name])]),expiry=field('Freigabe bis · optional','date',''),f=el('form','qol-grid');f.append(select.wrap,expiry.wrap);submit(ctx,f,'Mitbearbeitung freigeben',async()=>{if(!select.input.value)throw new Error('Bitte wähle ein Mitglied.');const expires=expiry.input.value?new Date(expiry.input.value+'T23:59:59').toISOString():null;await check(Raben.client().from('raben_entry_editors').insert({parent_type:type,parent_id:row.id,owner_id:owner,editor_id:select.input.value,expires_at:expires}));await refresh(ctx);});area.append(f);for(const e of rows){const p=note((members.find(m=>m.user_id===e.editor_id)?.display_name||'Mitglied')+(e.expires_at?' · bis '+new Date(e.expires_at).toLocaleDateString('de-DE'):''));p.append(button(ctx,'Mitbearbeitung entziehen',async()=>{await check(Raben.client().from('raben_entry_editors').delete().eq('parent_type',type).eq('parent_id',row.id).eq('editor_id',e.editor_id));await refresh(ctx);}));area.append(p);}}
   catch(error){if(live(ctx,epoch))ctx.report(error.message||Raben.errorMessage(error),true);loaded=false;}});
 };
 const history=async(ctx,item,card)=>{if(item.owner_id!==ctx.actor.user_id)return;const area=el('details','qol-panel');area.append(el('summary','','Eigene Profilversionen vergleichen'));card.append(area);let loaded=false;
  area.addEventListener('toggle',async()=>{if(!area.open||loaded)return;loaded=true;const epoch=ctx.epoch;try{await ctx.authorize();const rows=await check(Raben.client().from('raben_profile_versions').select('*').eq('item_id',item.id).eq('owner_id',ctx.actor.user_id).order('created_at',{ascending:false}).limit(30));if(!live(ctx,epoch)||!card.isConnected)return;area.append(note('Die letzten 30 Fassungen gehören nur dir. Beim Wiederherstellen bleiben die aktuellen Empfänger und Freigaben erhalten.'));if(!rows.length){area.append(note('Noch keine frühere Fassung. Nach der nächsten Änderung erscheint sie hier.'));return;}
   const choice=field('Frühere Fassung','select',rows[0].id,rows.map(v=>[v.id,new Date(v.created_at).toLocaleString('de-DE')+' · Version '+v.revision])),compare=el('div','profile-compare');area.append(choice.wrap,compare);
   const show=()=>{const v=rows.find(r=>r.id===choice.input.value);compare.replaceChildren();for(const [title,data] of [['Aktuell',item],['Frühere Fassung',v.snapshot.item]]){const panel=el('section','qol-card');panel.append(el('h5','',title),el('strong','',data.title),el('p','hub-body',data.body||''),el('pre','hub-body',JSON.stringify(data.details||{},null,2)));compare.append(panel);}const extras=note('Frühere Galerie: '+(v.snapshot.gallery?.length||0)+' Bilder · Theme: '+(v.snapshot.design?.theme||'Standard'));compare.lastChild.append(extras);};choice.input.addEventListener('change',show);show();area.append(button(ctx,'Gewählte Fassung wiederherstellen',async()=>{if(!confirm('Diese Fassung wiederherstellen? Deine aktuellen Freigaben bleiben erhalten.'))return;await check(Raben.client().rpc('raben_restore_own_profile_version',{p_version:choice.input.value,p_expected:item.revision}));await refresh(ctx);ctx.report('Eigene Profilversion wiederhergestellt. Die aktuellen Freigaben bleiben erhalten.');}));
  }catch(error){if(live(ctx,epoch))ctx.report(error.message||Raben.errorMessage(error),true);loaded=false;}});
 };
 const albums=async(ctx,item,images,gallery,card)=>{const epoch=ctx.epoch,rows=await check(Raben.client().from('raben_profile_albums').select('*').eq('item_id',item.id).order('sort_order'));if(!live(ctx,epoch)||!card.isConnected)return;const toolbar=el('div','album-toolbar'),select=field('Bilderalbum','select','all',[['all','Alle Bilder'],['','Ohne Album'],...rows.map(a=>[a.id,a.title])]);toolbar.append(select.wrap);gallery.before(toolbar);const apply=()=>{for(const image of images){const node=gallery.querySelector('[data-profile-image="'+image.id+'"]');if(node)node.hidden=select.input.value!=='all'&&(image.album_id||'')!==select.input.value;}};select.input.addEventListener('change',apply);
  if(item.owner_id!==ctx.actor.user_id)return;
  const name=field('Name des neuen Albums','text','');name.input.maxLength=100;toolbar.append(name.wrap,button(ctx,'Album erstellen',async()=>{if(!name.input.value.trim())throw new Error('Bitte gib dem Album einen Namen.');await check(Raben.client().from('raben_profile_albums').insert({item_id:item.id,owner_id:ctx.actor.user_id,title:name.input.value.trim(),sort_order:rows.length}));await refresh(ctx);}),button(ctx,'Album umbenennen',async()=>{if(!select.input.value||select.input.value==='all'||!name.input.value.trim())throw new Error('Wähle ein Album und gib seinen neuen Namen ein.');await check(Raben.client().from('raben_profile_albums').update({title:name.input.value.trim()}).eq('id',select.input.value));await refresh(ctx);}),button(ctx,'Album auflösen',async()=>{if(!select.input.value||select.input.value==='all')throw new Error('Bitte wähle ein Album.');await check(Raben.client().from('raben_profile_albums').delete().eq('id',select.input.value));await refresh(ctx);}));
  const save=async()=>{await check(Raben.client().rpc('raben_order_profile_gallery',{p_item:item.id,p_images:images.map(i=>({id:i.id,album_id:i.album_id||null}))}));const rows=await check(Raben.client().from('raben_profile_items').select('revision').eq('id',item.id).limit(1));if(rows[0])item.revision=rows[0].revision;ctx.report('Albumzuordnung und Bildreihenfolge gespeichert.');};
  const move=async(id,target)=>{const from=images.findIndex(i=>i.id===id),to=images.findIndex(i=>i.id===target);if(from<0||to<0||from===to)return;const old=[...images],image=images.splice(from,1)[0];images.splice(to,0,image);try{await save();for(const i of images)gallery.append(gallery.querySelector('[data-profile-image="'+i.id+'"]'));}catch(error){images.splice(0,images.length,...old);throw error;}};
  let dragged='';for(const image of images){const f=gallery.querySelector('[data-profile-image="'+image.id+'"]');if(!f)continue;const controls=el('div','album-image-order'),album=field('Album für dieses Bild','select',image.album_id||'',[['','Ohne Album'],...rows.map(a=>[a.id,a.title])]);album.input.addEventListener('change',async()=>{const previous=image.album_id;try{await ctx.authorize();image.album_id=album.input.value||null;await save();apply();}catch(error){image.album_id=previous;album.input.value=previous||'';ctx.report(error.message||Raben.errorMessage(error),true);}});controls.append(album.wrap,button(ctx,'↑',()=>{const index=images.indexOf(image);if(index>0)return move(image.id,images[index-1].id);}),button(ctx,'↓',()=>{const index=images.indexOf(image);if(index<images.length-1)return move(image.id,images[index+1].id);}));controls.children[1].setAttribute('aria-label','Bild früher anzeigen');controls.children[2].setAttribute('aria-label','Bild später anzeigen');f.append(controls);f.draggable=true;f.addEventListener('dragstart',event=>{if(event.target.closest('input,select,button')){event.preventDefault();return;}dragged=image.id;event.dataTransfer?.setData('text/plain',image.id);});f.addEventListener('dragover',event=>event.preventDefault());f.addEventListener('drop',async event=>{event.preventDefault();try{await ctx.authorize();await move(dragged||event.dataTransfer?.getData('text/plain'),image.id);}catch(error){ctx.report(error.message||Raben.errorMessage(error),true);}});}
 };
 const timeline=async(ctx,item,card)=>{if(item.kind!=='character')return;const area=el('details','qol-panel');area.append(el('summary','','Persönliche Charakter-Zeitleiste'));card.append(area);let loaded=false;area.addEventListener('toggle',async()=>{if(!area.open||loaded)return;loaded=true;const epoch=ctx.epoch;try{await ctx.authorize();const [automatic,links]=await Promise.all([check(Raben.client().from('raben_records').select('id,kind,title,details').eq('details->>speakerId',item.id).in('kind',['journal','event','chronicle']).order('details->>date').limit(200)),check(Raben.client().from('raben_character_timeline').select('*').eq('item_id',item.id).order('event_date').limit(200))]);if(!live(ctx,epoch)||!card.isConnected)return;const entries=automatic.map(r=>({type:'record',id:r.id,title:r.title,date:r.details.date||''}));for(const l of links){const rows=await check(Raben.client().from(l.parent_type==='record'?'raben_records':'raben_plots').select('id,title').eq('id',l.parent_id).limit(1));if(rows[0]&&!entries.some(e=>e.type===l.parent_type&&e.id===l.parent_id))entries.push({type:l.parent_type,id:l.parent_id,title:l.label||rows[0].title,date:l.event_date,linkId:l.id});}if(!live(ctx,epoch))return;const list=el('ol','timeline-list');entries.sort((a,b)=>a.date.localeCompare(b.date));for(const e of entries){const li=el('li','');li.append(el('time','field-note',e.date?new Date(e.date+'T12:00:00Z').toLocaleDateString('de-DE'):'Ohne Datum'),button(ctx,e.title,()=>RabenExpansion.openParent(ctx,e.type,e.id)));if(e.linkId&&item.owner_id===ctx.actor.user_id)li.append(button(ctx,'Verknüpfung entfernen',async()=>{await check(Raben.client().from('raben_character_timeline').delete().eq('id',e.linkId));await refresh(ctx);}));list.append(li);}area.append(entries.length?list:note('Noch keine freigegebenen Ereignisse für diesen Charakter.'));
   if(item.owner_id===ctx.actor.user_id){const [records,plots]=await Promise.all([check(Raben.client().from('raben_records').select('id,title,kind,details').in('kind',['journal','event','chronicle']).order('updated_at',{ascending:false}).limit(200)),check(Raben.client().from('raben_plots').select('id,title').order('updated_at',{ascending:false}).limit(200))]);if(!live(ctx,epoch))return;const target=field('Ereignis oder Plot ergänzen','select','',[['','Eintrag auswählen'],...records.map(r=>['record:'+r.id,r.title]),...plots.map(p=>['plot:'+p.id,'Plot · '+p.title])]),date=field('Datum auf der Zeitleiste','date',new Date().toISOString().slice(0,10)),f=el('form','qol-grid');target.input.required=true;date.input.required=true;f.append(target.wrap,date.wrap);submit(ctx,f,'Zur Zeitleiste hinzufügen',async()=>{const [type,id]=target.input.value.split(':');await check(Raben.client().from('raben_character_timeline').insert({item_id:item.id,owner_id:ctx.actor.user_id,parent_type:type,parent_id:id,event_date:date.input.value}));await refresh(ctx);});area.append(f);}
  }catch(error){if(live(ctx,epoch))ctx.report(error.message||Raben.errorMessage(error),true);loaded=false;}});};
 const tools=async(ctx,item,card)=>{history(ctx,item,card);timeline(ctx,item,card);await collaboration(ctx,'profile',item,card);};
 window.RabenProfilePlus={tools,albums,collaboration};
})();
