(() => {
 'use strict';const {el,check}=Raben,B='raben-profile-media';
 const themes={standard:{label:'Website-Standard',background:'#162127',panel:'#162127',text:'#f0eee8',accent:'#c8a46c',heading:'#edd7b0',font:'default',overlay:85},nordic:{label:'Nordischer Schild',background:'#172630',panel:'#172630',text:'#edf1f0',accent:'#cbaa70',heading:'#f2d9a8',font:'medieval',overlay:82},forest:{label:'Wald & Natur',background:'#142e23',panel:'#142e23',text:'#e4efe1',accent:'#8fc291',heading:'#d3ebad',font:'serif',overlay:80},aether:{label:'Aether & Licht',background:'#202945',panel:'#202945',text:'#e9efff',accent:'#a6b8ff',heading:'#e4d0ff',font:'palatino',overlay:80},abyss:{label:'Abyss & Schatten',background:'#25192c',panel:'#25192c',text:'#f0e5ef',accent:'#b884b0',heading:'#e4afc8',font:'serif',overlay:85},parchment:{label:'Altes Pergament',background:'#d8c7a0',panel:'#d8c7a0',text:'#30291e',accent:'#775327',heading:'#42301b',font:'medieval',overlay:90},custom:{label:'Eigenes Theme',background:'#18242a',panel:'#18242a',text:'#f0eee8',accent:'#c8a46c',heading:'#eed8b3',font:'default',overlay:82}};
 const valid=(ctx,e)=>!ctx.disposed&&ctx.epoch===e;
 const button=(text,fn)=>{const b=el('button','button outline small-button',text);b.type='button';b.addEventListener('click',fn);return b;};
 const field=(label,type,value,choices=[])=>{const w=el('label','form-field',label),i=el(type==='select'?'select':'input','');if(i.tagName==='INPUT')i.type=type;for(const [value,text] of choices){const o=el('option','',text);o.value=value;w.append();i.append(o);}if(type==='checkbox')i.checked=!!value;else if(type!=='file')i.value=value??'';w.append(i);return {wrap:w,input:i};};
 const range=(label,value,min=0,max=100)=>{const f=field(label,'range',value),out=el('output','field-note');Object.assign(f.input,{min:String(min),max:String(max),step:'1'});const show=()=>out.textContent=f.input.value+(max===100?' %':'');f.input.addEventListener('input',show);f.wrap.append(out);show();return f;};
 const paint=(host,theme,style={})=>{const values={...(themes[theme]||themes.standard),...style};host.classList.add('profile-styled');host.dataset.profileTheme=theme;for(const key of ['background','panel','text','accent','heading'])if(/^#[0-9a-f]{6}$/i.test(values[key]))host.style.setProperty('--profile-'+key,values[key]);host.style.setProperty('--profile-font',RabenSettings.fonts[values.font]||'var(--sans)');host.style.setProperty('--profile-overlay',Math.max(0,Math.min(100,values.overlay??82))/100);host.style.setProperty('--profile-image-opacity',Math.max(0,Math.min(100,values.imageOpacity??100))/100);};
 const download=async(ctx,path)=>{const e=ctx.epoch,blob=await check(Raben.client().storage.from(B).download(path));if(!valid(ctx,e))return '';const url=URL.createObjectURL(blob);ctx.urls.add(url);return url;};
 const prepare=async(ctx,item,form)=>{
  const e=ctx.epoch,rows=item?await check(Raben.client().from('raben_profile_styles').select('*').eq('item_id',item.id)):[];let saved=rows[0]||{theme:'standard',style:{},background_path:null,preview_path:null};if(!valid(ctx,e))return null;
  const section=el('fieldset','settings-fields profile-design-editor');section.append(el('legend','','Theme und Hintergrund'));
  const theme=field('Vorgefertigtes Theme','select',saved.theme,Object.entries(themes).map(([k,v])=>[k,v.label])),custom=el('div','reading-group'),inputs={};
  for(const [key,label,type] of [['background','Hintergrundfarbe','color'],['panel','Kartenfarbe','color'],['text','Textfarbe im Theme','color'],['heading','Überschriftenfarbe im Theme','color'],['accent','Akzentfarbe','color'],['font','Schrift im Theme','select']]){const x=field(label,type,saved.style[key]??themes[saved.theme]?.[key]??themes.custom[key],RabenSettings.fontChoices);inputs[key]=x.input;custom.append(x.wrap);}
  const foreground=range('Transparenz der vorderen Charakterbox',100-(saved.style.overlay??themes[saved.theme]?.overlay??85)),background=range('Transparenz des Charakter-Hintergrundbilds',100-(saved.style.imageOpacity??100));foreground.input.dataset.profileBoxTransparency='';background.input.dataset.profileImageTransparency='';
  const file=field('Eigenes Hintergrundbild · JPG, PNG oder WebP','file');file.input.accept='image/jpeg,image/png,image/webp';const remove=field('Hintergrundbild entfernen','checkbox',false),preview=el('article','profile-style-preview'),contrast=el('p','field-note contrast-check');contrast.setAttribute('role','status');preview.append(el('h4','',item?.title||'Dein Charakter'),el('p','hub-body','Ein Platz für deine Geschichte. Die Gestaltung teilt die Freigabe dieses Charakters.'));
  let previewUrl='',request=0;const readStyle=()=>({...theme.input.value==='custom'?Object.fromEntries(Object.entries(inputs).map(([k,i])=>[k,i.value])):{},overlay:100-Number(foreground.input.value),imageOpacity:100-Number(background.input.value)});
  const redraw=()=>{custom.hidden=theme.input.value!=='custom';const style=readStyle();paint(preview,theme.input.value,style);RabenQol.contrastNote(contrast,{...themes[theme.input.value],...style});if(previewUrl&&!remove.input.checked)preview.style.setProperty('--profile-image','url('+JSON.stringify(previewUrl)+')');else preview.style.removeProperty('--profile-image');};
  const loadBackground=async()=>{const n=++request;previewUrl='';redraw();if(saved.background_path){const url=await download(ctx,saved.preview_path||saved.background_path);if(valid(ctx,e)&&n===request&&!file.input.files?.length){previewUrl=url;redraw();}}};
  theme.input.addEventListener('change',redraw);[...Object.values(inputs),foreground.input,background.input].forEach(i=>{i.addEventListener('input',redraw);i.addEventListener('change',redraw);});remove.input.addEventListener('change',redraw);
  file.input.addEventListener('change',async()=>{const n=++request;try{const chosen=file.input.files?.[0];if(!chosen)return;await RabenMedia.validateFile(chosen,false);if(n!==request||!valid(ctx,e))return;previewUrl=URL.createObjectURL(chosen);ctx.urls.add(previewUrl);remove.input.checked=false;redraw();}catch(error){ctx.report(RabenMedia.errorMessage(error),true);}});
  const collect=async controls=>{let path=remove.input.checked?null:saved.background_path,thumb=remove.input.checked?null:saved.preview_path;if(file.input.files?.[0]&&!remove.input.checked){const result=await RabenPictures.upload(ctx,file.input.files[0],controls,B);path=result.imagePath;thumb=result.mediumPath||result.thumbPath;saved={...saved,background_path:path,preview_path:thumb};file.input.value='';}return {theme:theme.input.value,style:readStyle(),background_path:path,preview_path:thumb};};
  const templates=field('Eigene Theme-Vorlage','select','',[['','Vorlage auswählen']]),name=field('Name für eine neue Theme-Vorlage','text','');name.input.maxLength=100;const tools=el('div','theme-template-tools');let own=[];
  const refreshTemplates=async()=>{own=await check(Raben.client().from('raben_theme_templates').select('*').eq('user_id',ctx.actor.user_id).order('created_at',{ascending:false}));if(!valid(ctx,e))return;templates.input.replaceChildren();for(const [value,text] of [['','Vorlage auswählen'],...own.map(t=>[t.id,t.title])]){const o=el('option','',text);o.value=value;templates.input.append(o);}templates.input.value='';};
  templates.input.addEventListener('change',()=>{const selected=own.find(t=>t.id===templates.input.value);if(!selected)return;saved=selected;theme.input.value=selected.theme;for(const [key,i] of Object.entries(inputs))i.value=selected.style[key]??themes[selected.theme][key];foreground.input.value=100-(selected.style.overlay??themes[selected.theme].overlay);background.input.value=100-(selected.style.imageOpacity??100);foreground.input.dispatchEvent(new Event('input'));background.input.dispatchEvent(new Event('input'));file.input.value='';remove.input.checked=false;ctx.dirty=true;loadBackground().catch(()=>{});});
  const saveTemplate=RabenQol.button(ctx,'Theme als eigene Vorlage speichern',async()=>{if(!name.input.value.trim())throw new Error('Bitte gib der Vorlage einen Namen.');const design=await collect(RabenMedia.progressControls());await check(Raben.client().from('raben_theme_templates').insert({...design,title:name.input.value.trim(),user_id:ctx.actor.user_id}));await refreshTemplates();ctx.report('Eigene Theme-Vorlage gespeichert.');});
  const duplicate=RabenQol.button(ctx,'Vorlage duplizieren',async()=>{const selected=own.find(t=>t.id===templates.input.value);if(!selected)throw new Error('Bitte wähle zuerst eine Vorlage.');await check(Raben.client().from('raben_theme_templates').insert({user_id:ctx.actor.user_id,title:(name.input.value.trim()||selected.title+' · Kopie').slice(0,100),theme:selected.theme,style:selected.style,background_path:selected.background_path,preview_path:selected.preview_path}));await refreshTemplates();});
  tools.append(templates.wrap,name.wrap,saveTemplate,duplicate,RabenQol.button(ctx,'Gewählte Vorlage löschen',async()=>{if(!templates.input.value)throw new Error('Bitte wähle zuerst eine Vorlage.');await check(Raben.client().from('raben_theme_templates').delete().eq('id',templates.input.value).eq('user_id',ctx.actor.user_id));await refreshTemplates();}));
  section.append(theme.wrap,custom,foreground.wrap,background.wrap,file.wrap,remove.wrap,el('p','field-note','Box und Hintergrund lassen sich unabhängig einstellen: 0 % transparent = vollständig deckend; 100 % = vollständig durchsichtig. Deine Schrift bleibt sichtbar.'),preview,contrast,tools);form.append(section);redraw();loadBackground().catch(()=>{});await refreshTemplates();return {collect};
 };
 const render=async(ctx,item,card)=>{const e=ctx.epoch,rows=await check(Raben.client().from('raben_profile_styles').select('*').eq('item_id',item.id));if(!valid(ctx,e)||!card.isConnected||!rows.length)return;const style=rows[0];paint(card,style.theme,style.style);if(style.background_path)RabenQol.observe(ctx,card,async()=>{const url=await download(ctx,style.preview_path||style.background_path);if(valid(ctx,e)&&card.isConnected&&url)card.style.setProperty('--profile-image','url('+JSON.stringify(url)+')');});};
 const applyBanner=(header,profile)=>{const l=profile.banner_layout||{};header.style.setProperty('--profile-banner-opacity',String((profile.banner_opacity??100)/100));header.style.setProperty('--profile-banner-height',(l.height??260)+'px');header.style.setProperty('--profile-banner-x',(l.focusX??50)+'%');header.style.setProperty('--profile-banner-y',(l.focusY??50)+'%');header.style.setProperty('--profile-banner-zoom',String((l.zoom??100)/100));header.style.setProperty('--profile-banner-box-opacity',String((l.boxOpacity??74)/100));};
 const banner=async(ctx,profile,header)=>{if(!profile.banner_path)return;const e=ctx.epoch,url=await download(ctx,profile.banner_path);if(!valid(ctx,e)||!header.isConnected||!url)return;header.classList.add('profile-with-banner');header.style.setProperty('--profile-banner','url('+JSON.stringify(url)+')');applyBanner(header,profile);};
 const openBanner=(ctx,profile)=>{
  if(ctx.dirty&&!confirm('Ungespeicherte Eingaben verwerfen?'))return;const e=ctx.epoch,f=el('form','hub-editor profile-editor'),file=field('Banner hochladen','file');file.input.accept='image/jpeg,image/png,image/webp';const remove=field('Banner entfernen','checkbox',false),preview=el('div','profile-banner-preview profile-with-banner'),progress=RabenMedia.progressControls(),save=el('button','button small-button','Banner speichern');save.type='submit';
  const l=profile.banner_layout||{},controls={height:range('Bannerhöhe in Pixel',l.height??260,160,800),focusX:range('Bildfokus horizontal',l.focusX??50),focusY:range('Bildfokus vertikal',l.focusY??50),zoom:range('Bildausschnitt / Vergrößerung in Prozent',l.zoom??100,100,300),boxOpacity:range('Transparenz der vorderen Bannerbox',100-(l.boxOpacity??74))},transparency=range('Transparenz des Banner-Hintergrunds',100-(profile.banner_opacity??100));transparency.input.dataset.bannerTransparency='';controls.boxOpacity.input.dataset.bannerBoxTransparency='';const intro=el('div','profile-intro');intro.append(el('h4','',profile.display_name),el('p','field-note','Name und Text bleiben sichtbar.'));preview.append(intro);
  const layout=()=>Object.fromEntries(Object.entries(controls).map(([key,x])=>[key,key==='boxOpacity'?100-Number(x.input.value):Number(x.input.value)]));
  const redraw=()=>{applyBanner(preview,{banner_opacity:100-Number(transparency.input.value),banner_layout:layout()});preview.classList.toggle('banner-removed',remove.input.checked);};[transparency,...Object.values(controls),remove].forEach(x=>x.input.addEventListener('input',redraw));remove.input.addEventListener('change',redraw);redraw();
  f.append(el('h3','','Dein Clanprofil-Banner'),el('p','field-note','Banner, Bildfokus und vordere Box lassen sich direkt in der Vorschau einstellen.'),file.wrap,remove.wrap,...Object.values(controls).map(x=>x.wrap),transparency.wrap,preview,progress.wrap,save,button('Schließen',()=>{if(!ctx.dirty||confirm('Ungespeicherte Eingaben verwerfen?')){ctx.dirty=false;ctx.editor.replaceChildren();}}));ctx.editor.replaceChildren(f);ctx.dirty=false;
  f.addEventListener('input',()=>ctx.dirty=true);f.addEventListener('change',()=>ctx.dirty=true);file.input.addEventListener('change',async()=>{const chosen=file.input.files?.[0];if(!chosen)return;try{await RabenMedia.validateFile(chosen,false);if(!valid(ctx,e)||!f.isConnected)return;const url=URL.createObjectURL(chosen);ctx.urls.add(url);remove.input.checked=false;preview.style.setProperty('--profile-banner','url('+JSON.stringify(url)+')');redraw();}catch(error){ctx.report(RabenMedia.errorMessage(error),true);}});
  if(profile.banner_path)download(ctx,profile.banner_path).then(url=>{if(valid(ctx,e)&&f.isConnected&&!file.input.files?.length)preview.style.setProperty('--profile-banner','url('+JSON.stringify(url)+')');}).catch(()=>{});
  f.addEventListener('submit',async event=>{event.preventDefault();if(save.disabled)return;save.disabled=true;try{await ctx.authorize();let path=remove.input.checked?null:profile.banner_path||null;if(file.input.files?.[0]&&!remove.input.checked){const result=await RabenPictures.upload(ctx,file.input.files[0],progress,B);path=result.imagePath;}if(!valid(ctx,e)||!f.isConnected)return;await check(Raben.client().rpc('raben_save_banner_layout',{p_path:path,p_opacity:100-Number(transparency.input.value),p_layout:layout(),p_expected:profile.revision}));ctx.dirty=false;await RabenProfiles.mount(ctx);ctx.report('Dein Clanprofil-Banner und seine Transparenz sind gespeichert. Ausschnitt und Box-Transparenz sind übernommen.');}catch(error){if(valid(ctx,e))ctx.report(RabenProfiles.errorMessage(error),true);}finally{save.disabled=false;}});
 };
 window.RabenProfileDesign={prepare,render,banner,openBanner,themes,paint};
})();
