(() => {
 'use strict';const {el,check}=Raben,B='raben-profile-media';
 const themes={standard:{label:'Website-Standard',background:'#162127',panel:'#162127',text:'#f0eee8',accent:'#c8a46c',heading:'#edd7b0',font:'default',overlay:85},nordic:{label:'Nordischer Schild',background:'#172630',panel:'#172630',text:'#edf1f0',accent:'#cbaa70',heading:'#f2d9a8',font:'medieval',overlay:82},forest:{label:'Wald & Natur',background:'#142e23',panel:'#142e23',text:'#e4efe1',accent:'#8fc291',heading:'#d3ebad',font:'serif',overlay:80},aether:{label:'Aether & Licht',background:'#202945',panel:'#202945',text:'#e9efff',accent:'#a6b8ff',heading:'#e4d0ff',font:'palatino',overlay:80},abyss:{label:'Abyss & Schatten',background:'#25192c',panel:'#25192c',text:'#f0e5ef',accent:'#b884b0',heading:'#e4afc8',font:'serif',overlay:85},parchment:{label:'Altes Pergament',background:'#d8c7a0',panel:'#d8c7a0',text:'#30291e',accent:'#775327',heading:'#42301b',font:'medieval',overlay:90},custom:{label:'Eigenes Theme',background:'#18242a',panel:'#18242a',text:'#f0eee8',accent:'#c8a46c',heading:'#eed8b3',font:'default',overlay:82}};
 const valid=(ctx,e)=>!ctx.disposed&&ctx.epoch===e;
 const button=(text,fn)=>{const b=el('button','button outline small-button',text);b.type='button';b.addEventListener('click',fn);return b;};
 const field=(label,type,value,choices=[])=>{const w=el('label','form-field',label),i=el(type==='select'?'select':'input','');if(i.tagName==='INPUT')i.type=type;for(const [value,text] of choices){const o=el('option','',text);o.value=value;i.append(o);}if(type==='checkbox')i.checked=!!value;else if(type!=='file')i.value=value??'';w.append(i);return {wrap:w,input:i};};
 const paint=(host,theme,style={})=>{
  const values={...(themes[theme]||themes.standard),...style};host.classList.add('profile-styled');host.dataset.profileTheme=theme;
  for(const key of ['background','panel','text','accent','heading'])if(/^#[0-9a-f]{6}$/i.test(values[key]))host.style.setProperty('--profile-'+key,values[key]);
  host.style.setProperty('--profile-font',RabenSettings.fonts[values.font]||'var(--sans)');host.style.setProperty('--profile-overlay',Math.max(20,Math.min(95,Number(values.overlay)||82))/100);
 };
 const download=async(ctx,path)=>{const e=ctx.epoch,blob=await check(Raben.client().storage.from(B).download(path));if(!valid(ctx,e))return '';const url=URL.createObjectURL(blob);ctx.urls.add(url);return url;};
 const prepare=async(ctx,item,form)=>{
  const e=ctx.epoch,rows=item?await check(Raben.client().from('raben_profile_styles').select('*').eq('item_id',item.id)):[],saved=rows[0]||{theme:'standard',style:{},background_path:null,preview_path:null};if(!valid(ctx,e))return null;
  const section=el('fieldset','settings-fields profile-design-editor');section.append(el('legend','','Theme und Hintergrund'));
  const theme=field('Vorgefertigtes Theme','select',saved.theme,Object.entries(themes).map(([k,v])=>[k,v.label])),custom=el('div','reading-group'),inputs={};
  for(const [key,label,type] of [['background','Hintergrundfarbe','color'],['panel','Kartenfarbe','color'],['text','Textfarbe im Theme','color'],['heading','Überschriftenfarbe im Theme','color'],['accent','Akzentfarbe','color'],['font','Schrift im Theme','select'],['overlay','Deckkraft der Lesefläche in Prozent','number']]){const x=field(label,type,saved.style[key]??themes[saved.theme]?.[key]??themes.custom[key],RabenSettings.fontChoices);if(type==='number'){x.input.min=20;x.input.max=95;x.input.required=true;}inputs[key]=x.input;custom.append(x.wrap);}
  const file=field('Eigenes Hintergrundbild · JPG, PNG oder WebP','file');file.input.accept='image/jpeg,image/png,image/webp';const remove=field('Hintergrundbild entfernen','checkbox',false),preview=el('article','profile-style-preview');preview.append(el('h4','',item?.title||'Dein Charakter'),el('p','hub-body','Ein Platz für deine Geschichte. Die Gestaltung teilt die Freigabe dieses Charakters.'));
  let previewUrl='',request=0;const readStyle=()=>Object.fromEntries(Object.entries(inputs).map(([k,i])=>[k,k==='overlay'?Number(i.value):i.value]));
  const redraw=()=>{custom.hidden=theme.input.value!=='custom';paint(preview,theme.input.value,theme.input.value==='custom'?readStyle():{});if(previewUrl&&!remove.input.checked)preview.style.setProperty('--profile-image','url('+JSON.stringify(previewUrl)+')');else preview.style.removeProperty('--profile-image');};
  theme.input.addEventListener('change',redraw);Object.values(inputs).forEach(i=>{i.addEventListener('input',redraw);i.addEventListener('change',redraw);});remove.input.addEventListener('change',redraw);
  file.input.addEventListener('change',async()=>{const n=++request;try{const chosen=file.input.files?.[0];if(!chosen)return;await RabenMedia.validateFile(chosen,false);if(n!==request||!valid(ctx,e))return;previewUrl=URL.createObjectURL(chosen);ctx.urls.add(previewUrl);remove.input.checked=false;redraw();}catch(error){ctx.report(RabenMedia.errorMessage(error),true);}});
  section.append(theme.wrap,custom,file.wrap,remove.wrap,el('p','field-note','Themes und Hintergrundbilder sind nur für die Personen sichtbar, denen du diesen Charakter freigibst. Wähle „Eigenes Theme“ für eigene Farben und Schriften.'),preview);form.append(section);redraw();
  if(saved.background_path)download(ctx,saved.preview_path||saved.background_path).then(url=>{if(valid(ctx,e)&&!file.input.files?.length){previewUrl=url;redraw();}}).catch(()=>{});
  return {collect:async controls=>{let path=remove.input.checked?null:saved.background_path,thumb=remove.input.checked?null:saved.preview_path;if(file.input.files?.[0]){const result=await RabenPictures.upload(ctx,file.input.files[0],controls,B);path=result.imagePath;thumb=result.mediumPath||result.thumbPath;}return {theme:theme.input.value,style:theme.input.value==='custom'?readStyle():{},background_path:path,preview_path:thumb};}};
 };
 const render=async(ctx,item,card)=>{const e=ctx.epoch,rows=await check(Raben.client().from('raben_profile_styles').select('*').eq('item_id',item.id));if(!valid(ctx,e)||!card.isConnected||!rows.length)return;const style=rows[0];paint(card,style.theme,style.style);if(style.background_path){const url=await download(ctx,style.preview_path||style.background_path);if(valid(ctx,e)&&card.isConnected&&url)card.style.setProperty('--profile-image','url('+JSON.stringify(url)+')');}};
 const banner=async(ctx,profile,header)=>{if(!profile.banner_path)return;const e=ctx.epoch,url=await download(ctx,profile.banner_path);if(!valid(ctx,e)||!header.isConnected||!url)return;header.classList.add('profile-with-banner');header.style.setProperty('--profile-banner','url('+JSON.stringify(url)+')');header.style.setProperty('--profile-banner-opacity',String(Math.max(0,Math.min(100,profile.banner_opacity??100))/100));};
 const openBanner=(ctx,profile)=>{
  if(ctx.dirty&&!confirm('Ungespeicherte Eingaben verwerfen?'))return;const e=ctx.epoch,f=el('form','hub-editor profile-editor'),file=field('Banner hochladen','file');file.input.accept='image/jpeg,image/png,image/webp';const remove=field('Banner entfernen','checkbox',false),preview=el('div','profile-banner-preview'),progress=RabenMedia.progressControls(),save=el('button','button small-button','Banner speichern');save.type='submit';
  const transparency=field('Transparenz des Banner-Hintergrunds','range',100-(profile.banner_opacity??100)),value=el('output','field-note');transparency.input.min=0;transparency.input.max=100;transparency.input.step=1;transparency.input.dataset.bannerTransparency='';transparency.wrap.append(value);preview.classList.add('profile-with-banner');preview.append(el('h4','',profile.display_name),el('p','field-note','Der Text bleibt sichtbar, während du die Transparenz des Hintergrundbilds einstellst.'));
  const redraw=()=>{const n=Math.max(0,Math.min(100,Number(transparency.input.value)));value.textContent=n+' % transparent';preview.style.setProperty('--profile-banner-opacity',String((100-n)/100));preview.classList.toggle('banner-removed',remove.input.checked);};transparency.input.addEventListener('input',redraw);remove.input.addEventListener('change',redraw);redraw();
  f.append(el('h3','','Dein Clanprofil-Banner'),el('p','field-note','Das Banner erscheint hinter deinem Namen und Profilbild. Es ist für aktive Clanmitglieder sichtbar. Ein breites Bild, etwa 1600 × 500 Pixel, passt besonders gut.'),file.wrap,remove.wrap,transparency.wrap,el('p','field-note','0 %: das Bild ist vollständig sichtbar. 100 %: das Bild ist transparent. Namen, Profilbild und Schaltflächen behalten ihre Deckkraft.'),preview,progress.wrap,save,button('Schließen',()=>{if(!ctx.dirty||confirm('Ungespeicherte Eingaben verwerfen?')){ctx.dirty=false;ctx.editor.replaceChildren();}}));ctx.editor.replaceChildren(f);ctx.dirty=false;
  f.addEventListener('input',()=>ctx.dirty=true);f.addEventListener('change',()=>ctx.dirty=true);file.input.addEventListener('change',async()=>{const chosen=file.input.files?.[0];if(!chosen)return;try{await RabenMedia.validateFile(chosen,false);if(!valid(ctx,e)||!f.isConnected)return;const url=URL.createObjectURL(chosen);ctx.urls.add(url);remove.input.checked=false;preview.style.setProperty('--profile-banner','url('+JSON.stringify(url)+')');redraw();}catch(error){ctx.report(RabenMedia.errorMessage(error),true);}});
  if(profile.banner_path)download(ctx,profile.banner_path).then(url=>{if(valid(ctx,e)&&f.isConnected&&!file.input.files?.length)preview.style.setProperty('--profile-banner','url('+JSON.stringify(url)+')');}).catch(()=>{});
  f.addEventListener('submit',async event=>{event.preventDefault();if(save.disabled)return;save.disabled=true;try{await ctx.authorize();let path=remove.input.checked?null:profile.banner_path||null;if(file.input.files?.[0]&&!remove.input.checked){const result=await RabenPictures.upload(ctx,file.input.files[0],progress,B);path=result.mediumPath||result.imagePath;}if(!valid(ctx,e)||!f.isConnected)return;await check(Raben.client().rpc('raben_save_profile_banner_design',{p_path:path,p_opacity:100-Number(transparency.input.value),p_expected:profile.revision}));ctx.dirty=false;await RabenProfiles.mount(ctx);ctx.report('Dein Clanprofil-Banner und seine Transparenz sind gespeichert.');}catch(error){if(valid(ctx,e))ctx.report(RabenProfiles.errorMessage(error),true);}finally{save.disabled=false;}});
 };
 window.RabenProfileDesign={prepare,render,banner,openBanner,themes,paint};
})();
