(() => {
 'use strict';const {el,check}=Raben;const live=(ctx,e=ctx.epoch)=>!ctx.disposed&&ctx.epoch===e;
 const note=text=>el('p','field-note',text),field=(...args)=>RabenExpansion.field(...args);
 const busy=(node,value)=>{node.setAttribute('aria-busy',String(value));if('disabled' in node)node.disabled=value;};
 const button=(ctx,text,action)=>{const b=el('button','button outline small-button',text);b.type='button';b.addEventListener('click',async()=>{if(b.disabled)return;const epoch=ctx.epoch;busy(b,true);try{await ctx.authorize();if(!live(ctx,epoch))return;await action(b,epoch);}catch(error){if(live(ctx,epoch))ctx.report(error.message||Raben.errorMessage(error),true);}finally{busy(b,false);}});return b;};
 const submit=(ctx,form,text,action)=>{const b=el('button','button small-button',text);b.type='submit';form.append(b);form.addEventListener('submit',async event=>{event.preventDefault();if(b.disabled)return;busy(b,true);const epoch=ctx.epoch;try{await ctx.authorize();if(!live(ctx,epoch))return;await action(epoch); }catch(error){if(live(ctx,epoch))ctx.report(error.message||Raben.errorMessage(error),true);}finally{busy(b,false);}});return b;};
 const reload=ctx=>RabenExpansion.handlers[ctx.kind]?RabenExpansion.mount(ctx):ctx.reload();
 const observe=(ctx,node,action)=>{const epoch=ctx.epoch;const start=()=>{if(live(ctx,epoch)&&node.isConnected)return action();};if(!window.IntersectionObserver){Promise.resolve().then(start);return;}
  const observer=new IntersectionObserver(entries=>{if(entries.some(e=>e.isIntersecting)){observer.disconnect();ctx.lazyObservers?.delete(observer);Promise.resolve(start()).catch(()=>{});}},{rootMargin:'300px'});ctx.lazyObservers??=new Set();ctx.lazyObservers.add(observer);observer.observe(node);
 };
 const release=ctx=>{for(const o of ctx.lazyObservers||[])o.disconnect();ctx.lazyObservers?.clear();for(const d of ctx.draftControllers||[])d.dispose();ctx.draftControllers?.clear();};
 const paged=async(ctx,query,render,host=ctx.list)=>{const epoch=ctx.epoch;let offset=0,count=0;const list=el('div','qol-list'),more=button(ctx,'Weitere laden',()=>load()),status=note('');status.setAttribute('role','status');host.append(list,status,more);
  const load=async()=>{busy(list,true);status.textContent='Einträge werden geladen …';const result=await query().range(offset,offset+24);if(result.error)throw result.error;if(!live(ctx,epoch))return;offset+=result.data.length;count=Number(result.count??offset);for(const row of result.data){const card=await render(row);if(!live(ctx,epoch))return;if(card)list.append(card);}more.hidden=offset>=count;status.textContent=count?offset+' von '+count+' Einträgen':'';busy(list,false);if(!offset)list.append(note('Hier gibt es noch keine Einträge.'));};await load();return list;
 };
 // Text drafts are self-only in the database. Files, credentials and sharing choices are deliberately not captured.
 const draft=async(ctx,form,key,revision=null)=>{if(ctx.public||!ctx.actor?.user_id)return null;const epoch=ctx.epoch,uid=ctx.actor.user_id;let timer,pending=Promise.resolve(),disposed=false,cancelled=false,changed=false;
  const status=note('Private Textentwürfe werden auf deinem Konto gesichert.'),recover=el('div','draft-recovery');status.setAttribute('role','status');form.prepend(recover,status);
  const inputs=()=>[...form.querySelectorAll('textarea,input')].filter(i=>i.tagName==='TEXTAREA'||['text','search','email','url','number','date','time','datetime-local'].includes(i.type));
  const capture=()=>({revision,fields:inputs().map((i,index)=>({index,type:i.tagName==='TEXTAREA'?'textarea':i.type,value:i.value})),savedAt:new Date().toISOString()});
  const flush=()=>{if(disposed||!changed)return pending;changed=false;clearTimeout(timer);const payload=capture();pending=pending.catch(()=>{}).then(async()=>{if(cancelled)return;const actor=await ctx.authorize();if(actor?.user_id!==uid)return;await check(Raben.client().rpc('raben_save_private_draft',{p_key:key,p_payload:payload}));if(live(ctx,epoch)&&form.isConnected)status.textContent='Privater Entwurf gesichert · '+new Date().toLocaleTimeString('de-DE',{hour:'2-digit',minute:'2-digit'});}).catch(()=>{changed=true;if(live(ctx,epoch)&&form.isConnected)status.textContent='Entwurf wartet auf Verbindung. Lass dieses Formular geöffnet; die Sicherung wird erneut versucht.';});return pending;};
  const schedule=()=>{if(disposed)return;changed=true;clearTimeout(timer);timer=setTimeout(flush,700);};form.addEventListener('input',schedule);const retry=()=>flush();window.addEventListener('online',retry);
  const controller={clear:async()=>{cancelled=true;disposed=true;clearTimeout(timer);await pending.catch(()=>{});await check(Raben.client().from('raben_private_drafts').delete().eq('user_id',uid).eq('draft_key',key));controller.dispose();},dispose:()=>{if(disposed){clearTimeout(timer);}else {flush();disposed=true;}form.removeEventListener('input',schedule);window.removeEventListener('online',retry);ctx.draftControllers?.delete(controller);}};
  ctx.draftControllers??=new Set();ctx.draftControllers.add(controller);
  try{const rows=await check(Raben.client().from('raben_private_drafts').select('payload,updated_at').eq('user_id',uid).eq('draft_key',key).limit(1));if(live(ctx,epoch)&&form.isConnected&&rows[0]){const saved=rows[0].payload;
   recover.append(note(saved.revision!==revision?'Ein älterer Textentwurf ist vorhanden. Der Eintrag wurde inzwischen geändert; prüfe beide Texte vor dem Speichern.':'Ein privater Textentwurf ist vorhanden.'),button(ctx,'Textentwurf übernehmen',()=>{const fields=inputs();for(const f of saved.fields||[]){const i=fields[f.index];if(i&&(i.tagName==='TEXTAREA'?'textarea':i.type)===f.type)i.value=f.value;}ctx.dirty=true;form.dispatchEvent(new Event('input',{bubbles:true}));recover.remove();}),button(ctx,'Entwurf verwerfen',async()=>{await check(Raben.client().from('raben_private_drafts').delete().eq('user_id',uid).eq('draft_key',key));recover.remove();}));}}
  catch(_){status.textContent='Private Entwurfssicherung ist gerade nicht erreichbar.';}return controller;
 };
 const luminance=hex=>{const c=hex.replace('#','').match(/../g)?.map(n=>parseInt(n,16)/255)||[0,0,0];return c.map(v=>v<=.04045?v/12.92:((v+.055)/1.055)**2.4).reduce((s,v,i)=>s+v*[.2126,.7152,.0722][i],0);};
 const contrast=(a,b)=>{const x=luminance(a),y=luminance(b);return (Math.max(x,y)+.05)/(Math.min(x,y)+.05);};
 const contrastNote=(host,style)=>{const body=contrast(style.text,style.panel),heading=contrast(style.heading,style.panel);host.textContent='Kontrast: Text '+body.toFixed(2)+':1 · Überschriften '+heading.toFixed(2)+':1. '+(body>=4.5&&heading>=3?'Farben sind ausreichend kontrastreich.':'Wähle für bessere Lesbarkeit andere Farben.');host.classList.toggle('contrast-warning',body<4.5||heading<3);if(Number(style.overlay)<100)host.append(document.createTextNode(' Bei transparenter Lesefläche hängt der tatsächliche Kontrast zusätzlich vom Hintergrundbild ab.'));};
 let errorId=0;document.addEventListener('invalid',event=>{const input=event.target;if(!input.closest?.('form'))return;input.setAttribute('aria-invalid','true');let message=input.parentElement.querySelector('[data-field-error]');if(!message){message=el('span','field-error');message.dataset.fieldError='';message.id='field-error-'+(++errorId);message.setAttribute('role','alert');input.parentElement.append(message);input.setAttribute('aria-describedby',((input.getAttribute('aria-describedby')||'')+' '+message.id).trim());}message.textContent=input.validationMessage||'Bitte prüfe diese Eingabe.';if(input===input.form?.querySelector(':invalid'))input.focus?.();},true);
 document.addEventListener('input',event=>{const input=event.target;if(input.getAttribute?.('aria-invalid')==='true'&&input.validity?.valid){input.removeAttribute('aria-invalid');input.parentElement.querySelector('[data-field-error]')?.remove();}});
 window.addEventListener('raben-lock',()=>{for(const ctx of window.RabenCommunity?.contexts?.()||[])release(ctx);});
 window.RabenQol={live,note,field,busy,button,submit,reload,observe,release,paged,draft,contrast,contrastNote};
})();
