import assert from 'node:assert/strict';
import vm from 'node:vm';
import {readFile} from 'node:fs/promises';
import {stripTypeScriptTypes} from 'node:module';
import {calendarICS,foldICS} from '../supabase/functions/_shared/calendar.mjs';
import {createRPC,noCache,validPushEndpoint} from '../supabase/functions/_shared/server.mjs';
const event={id:'00000000-0000-4000-a000-000000005000',title:'Äöü, Reise; '+ '❄'.repeat(40),body:'Zwei\nZeilen',revision:3,details:{date:'2050-03-27',time:'01:30',duration:120,repeat:'weekly',repeatUntil:'2050-05-01',exceptions:['2050-04-03']}};
const text=calendarICS([event],'Mein Kalender',new Date('2050-03-01T00:00:00Z'));assert.match(text,/DTSTART;TZID=Europe\/Berlin:20500327T013000/);assert.match(text,/DURATION:PT120M/);assert.match(text,/SEQUENCE:3/);assert.match(text,/EXDATE;TZID=Europe\/Berlin:20500403T013000/);assert.ok(text.split('\r\n').every(l=>new TextEncoder().encode(l).length<=75));
const own=calendarICS([{...event,attending_dates:['2050-03-27','2050-04-03','2050-04-10']}]);assert.equal((own.match(/BEGIN:VEVENT/g)||[]).length,2);assert.ok(!own.includes('RRULE:FREQ=WEEKLY'));assert.ok(own.includes(event.id+'-2050-04-10@'));for(const url of ['http://fcm.googleapis.com/send','https://localhost/send','https://fcm.googleapis.com.evil.test/send','https://user:pass@fcm.googleapis.com/send','https://fcm.googleapis.com:8443/send'])assert.equal(validPushEndpoint(url),false);assert.equal(validPushEndpoint('https://updates.push.services.mozilla.com/wpush/v2/test'),true);
async function load(name,push=false){const calls=[],notifications=[],waiting=[];let result=null,fail=false,claim={publicKey:'TEST-PUBLIC',privateKey:'TEST-PRIVATE',jobs:[]};const globals={Request,Response,URL,JSON,Date,TextEncoder,AbortSignal,Promise,console,setTimeout,clearTimeout,Deno:{env:{get:key=>key==='SUPABASE_URL'?'https://backend.test':'TEST-SERVICE-KEY'},serve:()=>{}},EdgeRuntime:{waitUntil:p=>waiting.push(p)},fetch:async(url,options)=>{const rpc=url.split('/').pop(),args=JSON.parse(options.body);calls.push({rpc,args,headers:options.headers});if(fail)return new Response('{}',{status:403});if(rpc==='raben_claim_push_jobs')return Response.json(claim);if(rpc==='raben_complete_push_job')return Response.json(null);return Response.json(result);}};
 const context=vm.createContext(globals),source=stripTypeScriptTypes(await readFile(new URL('../supabase/functions/'+name+'/index.ts',import.meta.url),'utf8')),module=new vm.SourceTextModule(source,{context});
 const synthetic=namespace=>new vm.SyntheticModule(Object.keys(namespace),function(){for(const [key,value] of Object.entries(namespace))this.setExport(key,value);},{context});
 await module.link(async spec=>{if(spec.startsWith('npm:'))return synthetic({default:{sendNotification:async(subscription,payload,options)=>{notifications.push({subscription,payload:JSON.parse(payload),options});return {statusCode:201};}}});if(spec.endsWith('calendar.mjs'))return synthetic({calendarICS});return synthetic({createRPC:(url,key)=>async(rpc,args)=>{const response=await globals.fetch(url+'/rest/v1/rpc/'+rpc,{headers:{apikey:key,Authorization:'Bearer '+key},body:JSON.stringify(args)});if(!response.ok)throw new Error('rpc_error');return response.json();},noCache,validPushEndpoint});});await module.evaluate();return {handler:module.namespace.handler,calls,notifications,waiting,setResult:v=>result=v,setFailure:v=>fail=v,setClaim:v=>claim=v};}
const feed=await load('raben-calendar-feed');assert.equal((await feed.handler(new Request('https://edge.test/feed'))).status,404);assert.equal((await feed.handler(new Request('https://edge.test/feed?token=abc'))).status,404);assert.equal(feed.calls.length,0);const url='https://edge.test/feed?token='+'a'.repeat(64);assert.equal((await feed.handler(new Request(url,{method:'POST'}))).status,405);assert.equal((await feed.handler(new Request(url))).status,404);feed.setResult({title:'Kalender',events:[event]});const response=await feed.handler(new Request(url));assert.equal(response.status,200);assert.equal(response.headers.get('cache-control'),'private, no-store');assert.match(response.headers.get('content-type'),/text\/calendar/);assert.match(await response.text(),/SUMMARY:/);assert.equal(feed.calls[0].headers.apikey,'TEST-SERVICE-KEY');assert.equal(await (await feed.handler(new Request(url,{method:'HEAD'}))).text(),'');feed.setFailure(true);assert.equal((await feed.handler(new Request(url))).status,503);
const push=await load('raben-reminder-push',true);assert.equal((await push.handler(new Request('https://edge.test/push'))).status,405);assert.equal((await push.handler(new Request('https://edge.test/push',{method:'POST',body:'{}'}))).status,403);assert.equal(push.calls.length,0);const request=()=>new Request('https://edge.test/push',{method:'POST',body:JSON.stringify({secret:'b'.repeat(64)})});push.setFailure(true);assert.equal((await push.handler(request())).status,403);assert.equal(push.notifications.length,0);push.setFailure(false);push.setClaim({publicKey:'TEST-PUBLIC',privateKey:'TEST-PRIVATE',jobs:[{id:event.id,recordId:event.id,endpoint:'https://fcm.googleapis.com/fcm/send/test',p256dh:'TEST-KEY',auth:'TEST-AUTH'}]});assert.equal((await push.handler(request())).status,202);await Promise.all(push.waiting);assert.equal(push.notifications.length,1);assert.deepEqual(Object.keys(push.notifications[0].payload),['recordId']);assert.equal(push.calls.at(-1).args.p_status,201);push.setClaim({publicKey:'TEST-PUBLIC',privateKey:'TEST-PRIVATE',jobs:[{id:event.id,recordId:event.id,endpoint:'https://localhost/internal',p256dh:'TEST-KEY',auth:'TEST-AUTH'}]});await push.handler(request());await Promise.all(push.waiting);assert.equal(push.notifications.length,1);assert.equal(push.calls.at(-1).args.p_status,410);
console.log('PASS Edge: Berlin/DST-safe durations, chosen occurrences, escaping and UTF-8 folding, feed authentication/revocation responses, no caching, push secret rejection, generic payload, background delivery and endpoint restrictions.');
