import {fileURLToPath} from 'node:url';
process.chdir(fileURLToPath(new URL('../',import.meta.url)));
import {PGlite} from '@electric-sql/pglite';
import {readFile,readdir} from 'node:fs/promises';
import assert from 'node:assert/strict';
process.on('uncaughtException',error=>{console.error({message:error.message,code:error.code,query:error.query});process.exit(1);});
const db=new PGlite();
await db.exec(`
 create role anon; create role authenticated;
 create schema auth; create schema storage;
 create table auth.users(id uuid primary key);
 create table auth.identities(id uuid primary key default gen_random_uuid(),user_id uuid references auth.users,provider text,provider_id text,identity_data jsonb);
 create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;
 grant usage on schema auth,storage,public to anon,authenticated;
 grant execute on function auth.uid() to anon,authenticated;
 create table storage.buckets(id text primary key,name text,public boolean,file_size_limit bigint,allowed_mime_types text[]);
 create table storage.objects(id uuid primary key default gen_random_uuid(),bucket_id text references storage.buckets,name text,metadata jsonb default '{}');
 alter table storage.objects enable row level security;
 grant select,insert,delete on storage.objects to authenticated;
`);
const path='./supabase/';
await db.exec(await readFile(path+'schema.sql','utf8'));
await db.exec(await readFile(path+'seed.sql','utf8'));
await db.exec(await readFile(path+'migrations/20261007173747_clan_community_update.sql','utf8'));
await db.exec(await readFile(path+'migrations/20261007205601_media_history_roadmap.sql','utf8'));
await db.exec(await readFile(path+'migrations/20261008081126_repair_uploads_and_large_images.sql','utf8'));
await db.exec(await readFile(path+'migrations/20261008094929_private_clan_profiles.sql','utf8'));
await db.exec(await readFile(path+'migrations/20261008095414_profile_grant_index.sql','utf8'));
await db.exec(await readFile(path+'migrations/20261008105012_clan_account_identity.sql','utf8'));
for(const migration of (await readdir(path+'migrations')).filter(n=>n.includes('twenty_update_part')).sort())await db.exec(await readFile(path+'migrations/'+migration,'utf8'));
const {prepareSettings,verifySettingsAccess}=await import('./settings-access-cases.mjs');
await prepareSettings(db,path);
for(const migration of (await readdir(path+'migrations')).filter(n=>n.startsWith('20261009')).sort())await db.exec(await readFile(path+'migrations/'+migration,'utf8'));
assert.equal(Number((await db.query("select file_size_limit from storage.buckets where id='raben-media'")).rows[0].file_size_limit),50*1024*1024);
assert.equal(Number((await db.query("select file_size_limit from storage.buckets where id='raben-public'")).rows[0].file_size_limit),50*1024*1024);
const admin='00000000-0000-4000-a000-000000000001';
const member='00000000-0000-4000-a000-000000000002';
const other='00000000-0000-4000-a000-000000000003';
const blocked='00000000-0000-4000-a000-000000000004';
for(const [i,id] of [admin,member,other,blocked].entries()){
 await db.query('insert into auth.users(id) values ($1)',[id]);
 await db.query(`insert into public.raben_memberships(user_id,discord_id,display_name,status,role) values($1,$2,$3,$4,$5)`,[id,'12345678901234567'+i,'Test '+i,id===blocked?'blocked':'active',id===admin?'admin':'member']);
}
const as=async(role,id='')=>{await db.exec('reset role');await db.query("select set_config('request.jwt.claim.sub',$1,false)",[id]);await db.exec('set role '+role);};
const denied=async(sql,params=[])=>{let error;try{await db.query(sql,params);}catch(e){error=e;}assert.ok(error,sql+' must be rejected');return error;};
const scalar=async(sql,params=[])=>Object.values((await db.query(sql,params)).rows[0])[0];
await as('authenticated',member);
const audio=member+'/00000000-0000-4000-a000-000000000090.mp3';
await db.query("insert into storage.objects(bucket_id,name,metadata) values('raben-media',$1,'{\"size\":12,\"mimetype\":\"audio/mpeg\"}')",[audio]);
const media=await scalar("insert into public.raben_records(kind,title,details,visibility) values('media','RP-Aufnahme',$1,'draft') returning id",[{mediaType:'mp3',audioPath:audio}]);
await denied("insert into public.raben_records(kind,title,details,visibility) values('media','Selbst veröffentlichen',$1,'public')",[{mediaType:'mp3',audioPath:audio}]);
await denied("insert into public.raben_records(kind,title,details) values('media','Fremde Datei',$1)",[{mediaType:'mp3',audioPath:other+'/00000000-0000-4000-a000-000000000090.mp3'}]);
await denied("insert into public.raben_records(kind,title,details) values('media','Ungültiger Link',$1)",[{mediaType:'youtube',youtubeId:'javascript:alert(1)'}]);
assert.equal((await db.query('select * from public.raben_content_versions')).rows.length,0);
await denied('select public.raben_export_content()');
await denied('select public.raben_storage_inventory()');
await as('authenticated',other);
assert.equal((await db.query("select name from storage.objects where name=$1",[audio])).rows.length,0);
assert.equal((await db.query('select id from public.raben_records where id=$1',[media])).rows.length,0);
await as('authenticated',member);
await db.query("update public.raben_records set visibility='clan' where id=$1",[media]);
const character=await scalar("insert into public.raben_records(kind,title,details) values('character','Testcharakter',$1) returning id",[{mediaIds:[media],relatedIds:[],story:'Reise in den Norden'}]);
await denied('delete from public.raben_records where id=$1',[media]);
await as('authenticated',other);
assert.equal((await db.query('select name from storage.objects where name=$1',[audio])).rows.length,1);
await as('anon');
assert.equal((await db.query('select id from public.raben_records where id=$1',[media])).rows.length,0);
await denied('select * from public.raben_content_versions');
await denied('select public.raben_export_content()');
await as('authenticated',blocked);
assert.equal((await db.query('select name from storage.objects where name=$1',[audio])).rows.length,0);
await denied("insert into public.raben_records(kind,title,details) values('media','Gesperrter Upload',$1)",[{mediaType:'youtube',youtubeId:'M7lc1UVf-VE'}]);
await as('authenticated',admin);
await denied("update public.raben_records set visibility='public' where id=$1",[character]);
const publicAudio='00000000-0000-4000-a000-000000000091.mp3';
await db.query("insert into storage.objects(bucket_id,name,metadata) values('raben-public',$1,'{\"size\":12,\"mimetype\":\"audio/mpeg\"}')",[publicAudio]);
await db.query("update public.raben_records set details=details||$1::jsonb,visibility='public' where id=$2",[{publicAudio},media]);
await db.query("update public.raben_records set visibility='public' where id=$1",[character]);
await as('anon');
assert.equal((await db.query('select id from public.raben_records where id=$1',[media])).rows.length,1);
await as('authenticated',admin);
await db.query("update public.raben_site_content set content=content||$1::jsonb where id=1",[{rabenInfoMediaIds:[media]}]);
await denied("update public.raben_site_content set content=content||$1::jsonb where id=1",[{rabenInfoMediaIds:[character]}]);
const snapshot=await scalar("select id from public.raben_content_versions where entity_key=$1 and operation='insert' limit 1",[character]);
const revision=await scalar('select revision::text from public.raben_records where id=$1',[character]);
await denied('select public.raben_restore_version($1,$2)',[snapshot,'999']);
await db.query('select public.raben_restore_version($1,$2)',[snapshot,revision]);
assert.equal(await scalar('select visibility from public.raben_records where id=$1',[character]),'draft');
await as('authenticated',member);
await denied('select public.raben_restore_version($1,$2)',[snapshot,revision]);
// Published edits return to review and strip the released audio path.
await db.query("update public.raben_records set title='Neue Aufnahme',visibility='review' where id=$1",[media]);
assert.equal(await scalar("select details ? 'publicAudio' from public.raben_records where id=$1",[media]),false);
assert.equal((await db.query('delete from storage.objects where name=$1 returning name',[audio])).rows.length,0);
await as('authenticated',admin);
const inventory=await scalar('select public.raben_storage_inventory()');
assert.ok(inventory.find(f=>f.name===audio).used);
assert.ok(inventory.find(f=>f.name===audio).historyCount>0);
const backup=await scalar('select public.raben_export_content()');
assert.equal(backup.application,'schwarze-raben');assert.ok(backup.records.length>=2);assert.ok(backup.versions.length>=5);
const knowledge=await scalar("insert into public.raben_records(kind,title,details,created_by) values('knowledge','Wichtiges Wissen',$1,$2) returning id",[{pinned:true,category:'Handwerk'},member]);
await as('authenticated',member);
await db.query("update public.raben_records set title='Wissen geändert',details=$1 where id=$2",[{pinned:true,category:'Handwerk'},knowledge]);
await denied("update public.raben_records set details=$1 where id=$2",[{pinned:false},knowledge]);
await db.query('select public.raben_save_character_notes($1,$2)',[character,'Geheime Notiz']);
await as('authenticated',admin);
const noteSnapshot=await scalar("select id from public.raben_content_versions where source_table='raben_character_notes' and entity_key=$1 limit 1",[character]);
const expected=await scalar('select updated_at::text from public.raben_character_notes where record_id=$1',[character]);
await db.query('select public.raben_restore_version($1,$2)',[noteSnapshot,expected]);
const siteSnapshot=await scalar("select id from public.raben_content_versions where source_table='raben_site_content' and operation='baseline' limit 1");
const siteExpected=await scalar('select revision::text from public.raben_site_content where id=1');
await db.query('select public.raben_restore_version($1,$2)',[siteSnapshot,siteExpected]);

await denied('select public.raben_restore_backup_item($1,$2,$3,$4)',[{},'raben_records',character,'']);
const beforeImport=await scalar('select revision::text from public.raben_records where id=$1',[character]);
const importData={application:'schwarze-raben',schemaVersion:1,records:[{id:character,kind:'character',title:'Aus Sicherung',body:'Wiederhergestellt',details:{},created_by:member}]};
await db.query('select public.raben_restore_backup_item($1,$2,$3,$4)',[importData,'raben_records',character,beforeImport]);
assert.equal(await scalar('select title from public.raben_records where id=$1',[character]),'Aus Sicherung');
assert.deepEqual(await scalar("select details->'mediaIds' from public.raben_records where id=$1",[character]),[]);
await as('authenticated',member);await denied('select public.raben_restore_backup_item($1,$2,$3,$4)',[importData,'raben_records',character,beforeImport]);
await as('authenticated',admin);
console.log('PASS: private MP3 access, publication, attachments, ownership, blocked/anonymous access, protected history, restore conflicts, notes/site restore, exports, pinned knowledge and used-file retention.');
const {verifyProfiles}=await import('./profile-access-cases.mjs');
await verifyProfiles(db,{as,denied,scalar,admin,member,other,blocked});
const {verifyAccounts}=await import('./account-access-cases.mjs');
await verifyAccounts(db,{as,denied,scalar,admin,member,other,blocked});
const {verifyExpansion}=await import('./expansion-access-cases.mjs');
await verifyExpansion(db,{as,denied,scalar,admin,member,other,blocked});
await verifySettingsAccess({db,as,denied,scalar,admin,member,other,blocked});
const {verifyImprovements}=await import('./improvement-access-cases.mjs');
await verifyImprovements({db,as,denied,scalar,admin,member,other,blocked});
const {verifyPresentationAccess}=await import('./presentation-access-cases.mjs');
await verifyPresentationAccess({db,as,denied,scalar,admin,member,other,blocked});
await db.close();
